// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xms_disk_client_gui.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_xms_5fdisk_5fclient_5fgui_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_xms_5fdisk_5fclient_5fgui_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_xms_5fdisk_5fclient_5fgui_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_xms_5fdisk_5fclient_5fgui_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_xms_5fdisk_5fclient_5fgui_2eproto;
namespace xdisk {
class XDiskInfo;
struct XDiskInfoDefaultTypeInternal;
extern XDiskInfoDefaultTypeInternal _XDiskInfo_default_instance_;
class XFileInfo;
struct XFileInfoDefaultTypeInternal;
extern XFileInfoDefaultTypeInternal _XFileInfo_default_instance_;
class XFileInfoList;
struct XFileInfoListDefaultTypeInternal;
extern XFileInfoListDefaultTypeInternal _XFileInfoList_default_instance_;
class XFileSlice;
struct XFileSliceDefaultTypeInternal;
extern XFileSliceDefaultTypeInternal _XFileSlice_default_instance_;
class XFileTask;
struct XFileTaskDefaultTypeInternal;
extern XFileTaskDefaultTypeInternal _XFileTask_default_instance_;
class XFileTaskList;
struct XFileTaskListDefaultTypeInternal;
extern XFileTaskListDefaultTypeInternal _XFileTaskList_default_instance_;
class XGetDirReq;
struct XGetDirReqDefaultTypeInternal;
extern XGetDirReqDefaultTypeInternal _XGetDirReq_default_instance_;
}  // namespace xdisk
PROTOBUF_NAMESPACE_OPEN
template<> ::xdisk::XDiskInfo* Arena::CreateMaybeMessage<::xdisk::XDiskInfo>(Arena*);
template<> ::xdisk::XFileInfo* Arena::CreateMaybeMessage<::xdisk::XFileInfo>(Arena*);
template<> ::xdisk::XFileInfoList* Arena::CreateMaybeMessage<::xdisk::XFileInfoList>(Arena*);
template<> ::xdisk::XFileSlice* Arena::CreateMaybeMessage<::xdisk::XFileSlice>(Arena*);
template<> ::xdisk::XFileTask* Arena::CreateMaybeMessage<::xdisk::XFileTask>(Arena*);
template<> ::xdisk::XFileTaskList* Arena::CreateMaybeMessage<::xdisk::XFileTaskList>(Arena*);
template<> ::xdisk::XGetDirReq* Arena::CreateMaybeMessage<::xdisk::XGetDirReq>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace xdisk {

enum XFileMsgType : int {
  FILE_MSG_NONE = 0,
  GET_DIR_REQ = 1001,
  GET_DIR_RES = 1002,
  UPLOAD_FILE_REQ = 1003,
  UPLOAD_FILE_RES = 1004,
  SEND_SLICE_REQ = 1005,
  SEND_SLICE_RES = 1007,
  UPLOAD_FILE_END_REQ = 1008,
  UPLOAD_FILE_END_RES = 1009,
  DOWNLOAD_FILE_REQ = 1010,
  DOWNLOAD_FILE_RES = 1011,
  DOWNLOAD_FILE_BEGTIN = 10012,
  DOWNLOAD_SLICE_REQ = 1012,
  DOWNLOAD_SLICE_RES = 1013,
  DELETE_FILE_REQ = 1014,
  DELETE_FILE_RES = 1015,
  NEW_DIR_REQ = 1016,
  NEW_DIR_RES = 1017,
  GET_DISK_INFO_REQ = 1018,
  GET_DISK_INFO_RES = 1019,
  XFileMsgType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  XFileMsgType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool XFileMsgType_IsValid(int value);
constexpr XFileMsgType XFileMsgType_MIN = FILE_MSG_NONE;
constexpr XFileMsgType XFileMsgType_MAX = DOWNLOAD_FILE_BEGTIN;
constexpr int XFileMsgType_ARRAYSIZE = XFileMsgType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XFileMsgType_descriptor();
template<typename T>
inline const std::string& XFileMsgType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, XFileMsgType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function XFileMsgType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    XFileMsgType_descriptor(), enum_t_value);
}
inline bool XFileMsgType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, XFileMsgType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<XFileMsgType>(
    XFileMsgType_descriptor(), name, value);
}
// ===================================================================

class XDiskInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:xdisk.XDiskInfo) */ {
 public:
  inline XDiskInfo() : XDiskInfo(nullptr) {}
  ~XDiskInfo() override;
  explicit PROTOBUF_CONSTEXPR XDiskInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  XDiskInfo(const XDiskInfo& from);
  XDiskInfo(XDiskInfo&& from) noexcept
    : XDiskInfo() {
    *this = ::std::move(from);
  }

  inline XDiskInfo& operator=(const XDiskInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline XDiskInfo& operator=(XDiskInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const XDiskInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const XDiskInfo* internal_default_instance() {
    return reinterpret_cast<const XDiskInfo*>(
               &_XDiskInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(XDiskInfo& a, XDiskInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(XDiskInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(XDiskInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  XDiskInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<XDiskInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const XDiskInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const XDiskInfo& from) {
    XDiskInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(XDiskInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "xdisk.XDiskInfo";
  }
  protected:
  explicit XDiskInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAvailFieldNumber = 1,
    kTotalFieldNumber = 2,
    kFreeFieldNumber = 3,
    kDirSizeFieldNumber = 4,
  };
  // int64 avail = 1;
  void clear_avail();
  int64_t avail() const;
  void set_avail(int64_t value);
  private:
  int64_t _internal_avail() const;
  void _internal_set_avail(int64_t value);
  public:

  // int64 total = 2;
  void clear_total();
  int64_t total() const;
  void set_total(int64_t value);
  private:
  int64_t _internal_total() const;
  void _internal_set_total(int64_t value);
  public:

  // int64 free = 3;
  void clear_free();
  int64_t free() const;
  void set_free(int64_t value);
  private:
  int64_t _internal_free() const;
  void _internal_set_free(int64_t value);
  public:

  // int64 dir_size = 4;
  void clear_dir_size();
  int64_t dir_size() const;
  void set_dir_size(int64_t value);
  private:
  int64_t _internal_dir_size() const;
  void _internal_set_dir_size(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:xdisk.XDiskInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t avail_;
    int64_t total_;
    int64_t free_;
    int64_t dir_size_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_xms_5fdisk_5fclient_5fgui_2eproto;
};
// -------------------------------------------------------------------

class XGetDirReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:xdisk.XGetDirReq) */ {
 public:
  inline XGetDirReq() : XGetDirReq(nullptr) {}
  ~XGetDirReq() override;
  explicit PROTOBUF_CONSTEXPR XGetDirReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  XGetDirReq(const XGetDirReq& from);
  XGetDirReq(XGetDirReq&& from) noexcept
    : XGetDirReq() {
    *this = ::std::move(from);
  }

  inline XGetDirReq& operator=(const XGetDirReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline XGetDirReq& operator=(XGetDirReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const XGetDirReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const XGetDirReq* internal_default_instance() {
    return reinterpret_cast<const XGetDirReq*>(
               &_XGetDirReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(XGetDirReq& a, XGetDirReq& b) {
    a.Swap(&b);
  }
  inline void Swap(XGetDirReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(XGetDirReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  XGetDirReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<XGetDirReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const XGetDirReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const XGetDirReq& from) {
    XGetDirReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(XGetDirReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "xdisk.XGetDirReq";
  }
  protected:
  explicit XGetDirReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRootFieldNumber = 1,
  };
  // bytes root = 1;
  void clear_root();
  const std::string& root() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_root(ArgT0&& arg0, ArgT... args);
  std::string* mutable_root();
  PROTOBUF_NODISCARD std::string* release_root();
  void set_allocated_root(std::string* root);
  private:
  const std::string& _internal_root() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_root(const std::string& value);
  std::string* _internal_mutable_root();
  public:

  // @@protoc_insertion_point(class_scope:xdisk.XGetDirReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr root_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_xms_5fdisk_5fclient_5fgui_2eproto;
};
// -------------------------------------------------------------------

class XFileSlice final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:xdisk.XFileSlice) */ {
 public:
  inline XFileSlice() : XFileSlice(nullptr) {}
  ~XFileSlice() override;
  explicit PROTOBUF_CONSTEXPR XFileSlice(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  XFileSlice(const XFileSlice& from);
  XFileSlice(XFileSlice&& from) noexcept
    : XFileSlice() {
    *this = ::std::move(from);
  }

  inline XFileSlice& operator=(const XFileSlice& from) {
    CopyFrom(from);
    return *this;
  }
  inline XFileSlice& operator=(XFileSlice&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const XFileSlice& default_instance() {
    return *internal_default_instance();
  }
  static inline const XFileSlice* internal_default_instance() {
    return reinterpret_cast<const XFileSlice*>(
               &_XFileSlice_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(XFileSlice& a, XFileSlice& b) {
    a.Swap(&b);
  }
  inline void Swap(XFileSlice* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(XFileSlice* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  XFileSlice* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<XFileSlice>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const XFileSlice& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const XFileSlice& from) {
    XFileSlice::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(XFileSlice* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "xdisk.XFileSlice";
  }
  protected:
  explicit XFileSlice(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMd5FieldNumber = 4,
    kFileFieldNumber = 1,
    kSizeFieldNumber = 2,
    kOffsetFieldNumber = 3,
    kIsOkFieldNumber = 5,
  };
  // bytes md5 = 4;
  void clear_md5();
  const std::string& md5() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_md5(ArgT0&& arg0, ArgT... args);
  std::string* mutable_md5();
  PROTOBUF_NODISCARD std::string* release_md5();
  void set_allocated_md5(std::string* md5);
  private:
  const std::string& _internal_md5() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_md5(const std::string& value);
  std::string* _internal_mutable_md5();
  public:

  // .xdisk.XFileInfo file = 1;
  bool has_file() const;
  private:
  bool _internal_has_file() const;
  public:
  void clear_file();
  const ::xdisk::XFileInfo& file() const;
  PROTOBUF_NODISCARD ::xdisk::XFileInfo* release_file();
  ::xdisk::XFileInfo* mutable_file();
  void set_allocated_file(::xdisk::XFileInfo* file);
  private:
  const ::xdisk::XFileInfo& _internal_file() const;
  ::xdisk::XFileInfo* _internal_mutable_file();
  public:
  void unsafe_arena_set_allocated_file(
      ::xdisk::XFileInfo* file);
  ::xdisk::XFileInfo* unsafe_arena_release_file();

  // int64 size = 2;
  void clear_size();
  int64_t size() const;
  void set_size(int64_t value);
  private:
  int64_t _internal_size() const;
  void _internal_set_size(int64_t value);
  public:

  // int64 offset = 3;
  void clear_offset();
  int64_t offset() const;
  void set_offset(int64_t value);
  private:
  int64_t _internal_offset() const;
  void _internal_set_offset(int64_t value);
  public:

  // bool is_ok = 5;
  void clear_is_ok();
  bool is_ok() const;
  void set_is_ok(bool value);
  private:
  bool _internal_is_ok() const;
  void _internal_set_is_ok(bool value);
  public:

  // @@protoc_insertion_point(class_scope:xdisk.XFileSlice)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr md5_;
    ::xdisk::XFileInfo* file_;
    int64_t size_;
    int64_t offset_;
    bool is_ok_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_xms_5fdisk_5fclient_5fgui_2eproto;
};
// -------------------------------------------------------------------

class XFileInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:xdisk.XFileInfo) */ {
 public:
  inline XFileInfo() : XFileInfo(nullptr) {}
  ~XFileInfo() override;
  explicit PROTOBUF_CONSTEXPR XFileInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  XFileInfo(const XFileInfo& from);
  XFileInfo(XFileInfo&& from) noexcept
    : XFileInfo() {
    *this = ::std::move(from);
  }

  inline XFileInfo& operator=(const XFileInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline XFileInfo& operator=(XFileInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const XFileInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const XFileInfo* internal_default_instance() {
    return reinterpret_cast<const XFileInfo*>(
               &_XFileInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(XFileInfo& a, XFileInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(XFileInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(XFileInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  XFileInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<XFileInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const XFileInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const XFileInfo& from) {
    XFileInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(XFileInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "xdisk.XFileInfo";
  }
  protected:
  explicit XFileInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFilenameFieldNumber = 1,
    kFiledirFieldNumber = 2,
    kFiletimeFieldNumber = 4,
    kMd5FieldNumber = 6,
    kLocalPathFieldNumber = 7,
    kPasswordFieldNumber = 11,
    kFilesizeFieldNumber = 3,
    kNetSizeFieldNumber = 8,
    kOriSizeFieldNumber = 10,
    kIsDirFieldNumber = 5,
    kIsEncFieldNumber = 9,
  };
  // bytes filename = 1;
  void clear_filename();
  const std::string& filename() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_filename(ArgT0&& arg0, ArgT... args);
  std::string* mutable_filename();
  PROTOBUF_NODISCARD std::string* release_filename();
  void set_allocated_filename(std::string* filename);
  private:
  const std::string& _internal_filename() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_filename(const std::string& value);
  std::string* _internal_mutable_filename();
  public:

  // bytes filedir = 2;
  void clear_filedir();
  const std::string& filedir() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_filedir(ArgT0&& arg0, ArgT... args);
  std::string* mutable_filedir();
  PROTOBUF_NODISCARD std::string* release_filedir();
  void set_allocated_filedir(std::string* filedir);
  private:
  const std::string& _internal_filedir() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_filedir(const std::string& value);
  std::string* _internal_mutable_filedir();
  public:

  // string filetime = 4;
  void clear_filetime();
  const std::string& filetime() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_filetime(ArgT0&& arg0, ArgT... args);
  std::string* mutable_filetime();
  PROTOBUF_NODISCARD std::string* release_filetime();
  void set_allocated_filetime(std::string* filetime);
  private:
  const std::string& _internal_filetime() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_filetime(const std::string& value);
  std::string* _internal_mutable_filetime();
  public:

  // bytes md5 = 6;
  void clear_md5();
  const std::string& md5() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_md5(ArgT0&& arg0, ArgT... args);
  std::string* mutable_md5();
  PROTOBUF_NODISCARD std::string* release_md5();
  void set_allocated_md5(std::string* md5);
  private:
  const std::string& _internal_md5() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_md5(const std::string& value);
  std::string* _internal_mutable_md5();
  public:

  // bytes local_path = 7;
  void clear_local_path();
  const std::string& local_path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_local_path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_local_path();
  PROTOBUF_NODISCARD std::string* release_local_path();
  void set_allocated_local_path(std::string* local_path);
  private:
  const std::string& _internal_local_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_local_path(const std::string& value);
  std::string* _internal_mutable_local_path();
  public:

  // bytes password = 11;
  void clear_password();
  const std::string& password() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_password(ArgT0&& arg0, ArgT... args);
  std::string* mutable_password();
  PROTOBUF_NODISCARD std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // int64 filesize = 3;
  void clear_filesize();
  int64_t filesize() const;
  void set_filesize(int64_t value);
  private:
  int64_t _internal_filesize() const;
  void _internal_set_filesize(int64_t value);
  public:

  // int64 net_size = 8;
  void clear_net_size();
  int64_t net_size() const;
  void set_net_size(int64_t value);
  private:
  int64_t _internal_net_size() const;
  void _internal_set_net_size(int64_t value);
  public:

  // int64 ori_size = 10;
  void clear_ori_size();
  int64_t ori_size() const;
  void set_ori_size(int64_t value);
  private:
  int64_t _internal_ori_size() const;
  void _internal_set_ori_size(int64_t value);
  public:

  // bool is_dir = 5;
  void clear_is_dir();
  bool is_dir() const;
  void set_is_dir(bool value);
  private:
  bool _internal_is_dir() const;
  void _internal_set_is_dir(bool value);
  public:

  // bool is_enc = 9;
  void clear_is_enc();
  bool is_enc() const;
  void set_is_enc(bool value);
  private:
  bool _internal_is_enc() const;
  void _internal_set_is_enc(bool value);
  public:

  // @@protoc_insertion_point(class_scope:xdisk.XFileInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr filename_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr filedir_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr filetime_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr md5_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr local_path_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
    int64_t filesize_;
    int64_t net_size_;
    int64_t ori_size_;
    bool is_dir_;
    bool is_enc_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_xms_5fdisk_5fclient_5fgui_2eproto;
};
// -------------------------------------------------------------------

class XFileInfoList final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:xdisk.XFileInfoList) */ {
 public:
  inline XFileInfoList() : XFileInfoList(nullptr) {}
  ~XFileInfoList() override;
  explicit PROTOBUF_CONSTEXPR XFileInfoList(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  XFileInfoList(const XFileInfoList& from);
  XFileInfoList(XFileInfoList&& from) noexcept
    : XFileInfoList() {
    *this = ::std::move(from);
  }

  inline XFileInfoList& operator=(const XFileInfoList& from) {
    CopyFrom(from);
    return *this;
  }
  inline XFileInfoList& operator=(XFileInfoList&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const XFileInfoList& default_instance() {
    return *internal_default_instance();
  }
  static inline const XFileInfoList* internal_default_instance() {
    return reinterpret_cast<const XFileInfoList*>(
               &_XFileInfoList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(XFileInfoList& a, XFileInfoList& b) {
    a.Swap(&b);
  }
  inline void Swap(XFileInfoList* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(XFileInfoList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  XFileInfoList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<XFileInfoList>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const XFileInfoList& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const XFileInfoList& from) {
    XFileInfoList::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(XFileInfoList* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "xdisk.XFileInfoList";
  }
  protected:
  explicit XFileInfoList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFilesFieldNumber = 4,
  };
  // repeated .xdisk.XFileInfo files = 4;
  int files_size() const;
  private:
  int _internal_files_size() const;
  public:
  void clear_files();
  ::xdisk::XFileInfo* mutable_files(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::xdisk::XFileInfo >*
      mutable_files();
  private:
  const ::xdisk::XFileInfo& _internal_files(int index) const;
  ::xdisk::XFileInfo* _internal_add_files();
  public:
  const ::xdisk::XFileInfo& files(int index) const;
  ::xdisk::XFileInfo* add_files();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::xdisk::XFileInfo >&
      files() const;

  // @@protoc_insertion_point(class_scope:xdisk.XFileInfoList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::xdisk::XFileInfo > files_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_xms_5fdisk_5fclient_5fgui_2eproto;
};
// -------------------------------------------------------------------

class XFileTask final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:xdisk.XFileTask) */ {
 public:
  inline XFileTask() : XFileTask(nullptr) {}
  ~XFileTask() override;
  explicit PROTOBUF_CONSTEXPR XFileTask(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  XFileTask(const XFileTask& from);
  XFileTask(XFileTask&& from) noexcept
    : XFileTask() {
    *this = ::std::move(from);
  }

  inline XFileTask& operator=(const XFileTask& from) {
    CopyFrom(from);
    return *this;
  }
  inline XFileTask& operator=(XFileTask&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const XFileTask& default_instance() {
    return *internal_default_instance();
  }
  static inline const XFileTask* internal_default_instance() {
    return reinterpret_cast<const XFileTask*>(
               &_XFileTask_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(XFileTask& a, XFileTask& b) {
    a.Swap(&b);
  }
  inline void Swap(XFileTask* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(XFileTask* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  XFileTask* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<XFileTask>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const XFileTask& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const XFileTask& from) {
    XFileTask::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(XFileTask* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "xdisk.XFileTask";
  }
  protected:
  explicit XFileTask(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTasktimeFieldNumber = 6,
    kFileFieldNumber = 9,
    kIndexFieldNumber = 1,
    kIsCompleteFieldNumber = 7,
    kIsSecFieldNumber = 8,
    kIsUploadFieldNumber = 10,
  };
  // string tasktime = 6;
  void clear_tasktime();
  const std::string& tasktime() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_tasktime(ArgT0&& arg0, ArgT... args);
  std::string* mutable_tasktime();
  PROTOBUF_NODISCARD std::string* release_tasktime();
  void set_allocated_tasktime(std::string* tasktime);
  private:
  const std::string& _internal_tasktime() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_tasktime(const std::string& value);
  std::string* _internal_mutable_tasktime();
  public:

  // .xdisk.XFileInfo file = 9;
  bool has_file() const;
  private:
  bool _internal_has_file() const;
  public:
  void clear_file();
  const ::xdisk::XFileInfo& file() const;
  PROTOBUF_NODISCARD ::xdisk::XFileInfo* release_file();
  ::xdisk::XFileInfo* mutable_file();
  void set_allocated_file(::xdisk::XFileInfo* file);
  private:
  const ::xdisk::XFileInfo& _internal_file() const;
  ::xdisk::XFileInfo* _internal_mutable_file();
  public:
  void unsafe_arena_set_allocated_file(
      ::xdisk::XFileInfo* file);
  ::xdisk::XFileInfo* unsafe_arena_release_file();

  // int32 index = 1;
  void clear_index();
  int32_t index() const;
  void set_index(int32_t value);
  private:
  int32_t _internal_index() const;
  void _internal_set_index(int32_t value);
  public:

  // bool is_complete = 7;
  void clear_is_complete();
  bool is_complete() const;
  void set_is_complete(bool value);
  private:
  bool _internal_is_complete() const;
  void _internal_set_is_complete(bool value);
  public:

  // bool is_sec = 8;
  void clear_is_sec();
  bool is_sec() const;
  void set_is_sec(bool value);
  private:
  bool _internal_is_sec() const;
  void _internal_set_is_sec(bool value);
  public:

  // bool is_upload = 10;
  void clear_is_upload();
  bool is_upload() const;
  void set_is_upload(bool value);
  private:
  bool _internal_is_upload() const;
  void _internal_set_is_upload(bool value);
  public:

  // @@protoc_insertion_point(class_scope:xdisk.XFileTask)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr tasktime_;
    ::xdisk::XFileInfo* file_;
    int32_t index_;
    bool is_complete_;
    bool is_sec_;
    bool is_upload_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_xms_5fdisk_5fclient_5fgui_2eproto;
};
// -------------------------------------------------------------------

class XFileTaskList final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:xdisk.XFileTaskList) */ {
 public:
  inline XFileTaskList() : XFileTaskList(nullptr) {}
  ~XFileTaskList() override;
  explicit PROTOBUF_CONSTEXPR XFileTaskList(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  XFileTaskList(const XFileTaskList& from);
  XFileTaskList(XFileTaskList&& from) noexcept
    : XFileTaskList() {
    *this = ::std::move(from);
  }

  inline XFileTaskList& operator=(const XFileTaskList& from) {
    CopyFrom(from);
    return *this;
  }
  inline XFileTaskList& operator=(XFileTaskList&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const XFileTaskList& default_instance() {
    return *internal_default_instance();
  }
  static inline const XFileTaskList* internal_default_instance() {
    return reinterpret_cast<const XFileTaskList*>(
               &_XFileTaskList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(XFileTaskList& a, XFileTaskList& b) {
    a.Swap(&b);
  }
  inline void Swap(XFileTaskList* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(XFileTaskList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  XFileTaskList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<XFileTaskList>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const XFileTaskList& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const XFileTaskList& from) {
    XFileTaskList::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(XFileTaskList* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "xdisk.XFileTaskList";
  }
  protected:
  explicit XFileTaskList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUploadsFieldNumber = 1,
    kDownloadsFieldNumber = 2,
  };
  // repeated .xdisk.XFileTask uploads = 1;
  int uploads_size() const;
  private:
  int _internal_uploads_size() const;
  public:
  void clear_uploads();
  ::xdisk::XFileTask* mutable_uploads(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::xdisk::XFileTask >*
      mutable_uploads();
  private:
  const ::xdisk::XFileTask& _internal_uploads(int index) const;
  ::xdisk::XFileTask* _internal_add_uploads();
  public:
  const ::xdisk::XFileTask& uploads(int index) const;
  ::xdisk::XFileTask* add_uploads();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::xdisk::XFileTask >&
      uploads() const;

  // repeated .xdisk.XFileTask downloads = 2;
  int downloads_size() const;
  private:
  int _internal_downloads_size() const;
  public:
  void clear_downloads();
  ::xdisk::XFileTask* mutable_downloads(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::xdisk::XFileTask >*
      mutable_downloads();
  private:
  const ::xdisk::XFileTask& _internal_downloads(int index) const;
  ::xdisk::XFileTask* _internal_add_downloads();
  public:
  const ::xdisk::XFileTask& downloads(int index) const;
  ::xdisk::XFileTask* add_downloads();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::xdisk::XFileTask >&
      downloads() const;

  // @@protoc_insertion_point(class_scope:xdisk.XFileTaskList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::xdisk::XFileTask > uploads_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::xdisk::XFileTask > downloads_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_xms_5fdisk_5fclient_5fgui_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// XDiskInfo

// int64 avail = 1;
inline void XDiskInfo::clear_avail() {
  _impl_.avail_ = int64_t{0};
}
inline int64_t XDiskInfo::_internal_avail() const {
  return _impl_.avail_;
}
inline int64_t XDiskInfo::avail() const {
  // @@protoc_insertion_point(field_get:xdisk.XDiskInfo.avail)
  return _internal_avail();
}
inline void XDiskInfo::_internal_set_avail(int64_t value) {
  
  _impl_.avail_ = value;
}
inline void XDiskInfo::set_avail(int64_t value) {
  _internal_set_avail(value);
  // @@protoc_insertion_point(field_set:xdisk.XDiskInfo.avail)
}

// int64 total = 2;
inline void XDiskInfo::clear_total() {
  _impl_.total_ = int64_t{0};
}
inline int64_t XDiskInfo::_internal_total() const {
  return _impl_.total_;
}
inline int64_t XDiskInfo::total() const {
  // @@protoc_insertion_point(field_get:xdisk.XDiskInfo.total)
  return _internal_total();
}
inline void XDiskInfo::_internal_set_total(int64_t value) {
  
  _impl_.total_ = value;
}
inline void XDiskInfo::set_total(int64_t value) {
  _internal_set_total(value);
  // @@protoc_insertion_point(field_set:xdisk.XDiskInfo.total)
}

// int64 free = 3;
inline void XDiskInfo::clear_free() {
  _impl_.free_ = int64_t{0};
}
inline int64_t XDiskInfo::_internal_free() const {
  return _impl_.free_;
}
inline int64_t XDiskInfo::free() const {
  // @@protoc_insertion_point(field_get:xdisk.XDiskInfo.free)
  return _internal_free();
}
inline void XDiskInfo::_internal_set_free(int64_t value) {
  
  _impl_.free_ = value;
}
inline void XDiskInfo::set_free(int64_t value) {
  _internal_set_free(value);
  // @@protoc_insertion_point(field_set:xdisk.XDiskInfo.free)
}

// int64 dir_size = 4;
inline void XDiskInfo::clear_dir_size() {
  _impl_.dir_size_ = int64_t{0};
}
inline int64_t XDiskInfo::_internal_dir_size() const {
  return _impl_.dir_size_;
}
inline int64_t XDiskInfo::dir_size() const {
  // @@protoc_insertion_point(field_get:xdisk.XDiskInfo.dir_size)
  return _internal_dir_size();
}
inline void XDiskInfo::_internal_set_dir_size(int64_t value) {
  
  _impl_.dir_size_ = value;
}
inline void XDiskInfo::set_dir_size(int64_t value) {
  _internal_set_dir_size(value);
  // @@protoc_insertion_point(field_set:xdisk.XDiskInfo.dir_size)
}

// -------------------------------------------------------------------

// XGetDirReq

// bytes root = 1;
inline void XGetDirReq::clear_root() {
  _impl_.root_.ClearToEmpty();
}
inline const std::string& XGetDirReq::root() const {
  // @@protoc_insertion_point(field_get:xdisk.XGetDirReq.root)
  return _internal_root();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void XGetDirReq::set_root(ArgT0&& arg0, ArgT... args) {
 
 _impl_.root_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:xdisk.XGetDirReq.root)
}
inline std::string* XGetDirReq::mutable_root() {
  std::string* _s = _internal_mutable_root();
  // @@protoc_insertion_point(field_mutable:xdisk.XGetDirReq.root)
  return _s;
}
inline const std::string& XGetDirReq::_internal_root() const {
  return _impl_.root_.Get();
}
inline void XGetDirReq::_internal_set_root(const std::string& value) {
  
  _impl_.root_.Set(value, GetArenaForAllocation());
}
inline std::string* XGetDirReq::_internal_mutable_root() {
  
  return _impl_.root_.Mutable(GetArenaForAllocation());
}
inline std::string* XGetDirReq::release_root() {
  // @@protoc_insertion_point(field_release:xdisk.XGetDirReq.root)
  return _impl_.root_.Release();
}
inline void XGetDirReq::set_allocated_root(std::string* root) {
  if (root != nullptr) {
    
  } else {
    
  }
  _impl_.root_.SetAllocated(root, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.root_.IsDefault()) {
    _impl_.root_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:xdisk.XGetDirReq.root)
}

// -------------------------------------------------------------------

// XFileSlice

// .xdisk.XFileInfo file = 1;
inline bool XFileSlice::_internal_has_file() const {
  return this != internal_default_instance() && _impl_.file_ != nullptr;
}
inline bool XFileSlice::has_file() const {
  return _internal_has_file();
}
inline void XFileSlice::clear_file() {
  if (GetArenaForAllocation() == nullptr && _impl_.file_ != nullptr) {
    delete _impl_.file_;
  }
  _impl_.file_ = nullptr;
}
inline const ::xdisk::XFileInfo& XFileSlice::_internal_file() const {
  const ::xdisk::XFileInfo* p = _impl_.file_;
  return p != nullptr ? *p : reinterpret_cast<const ::xdisk::XFileInfo&>(
      ::xdisk::_XFileInfo_default_instance_);
}
inline const ::xdisk::XFileInfo& XFileSlice::file() const {
  // @@protoc_insertion_point(field_get:xdisk.XFileSlice.file)
  return _internal_file();
}
inline void XFileSlice::unsafe_arena_set_allocated_file(
    ::xdisk::XFileInfo* file) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.file_);
  }
  _impl_.file_ = file;
  if (file) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:xdisk.XFileSlice.file)
}
inline ::xdisk::XFileInfo* XFileSlice::release_file() {
  
  ::xdisk::XFileInfo* temp = _impl_.file_;
  _impl_.file_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::xdisk::XFileInfo* XFileSlice::unsafe_arena_release_file() {
  // @@protoc_insertion_point(field_release:xdisk.XFileSlice.file)
  
  ::xdisk::XFileInfo* temp = _impl_.file_;
  _impl_.file_ = nullptr;
  return temp;
}
inline ::xdisk::XFileInfo* XFileSlice::_internal_mutable_file() {
  
  if (_impl_.file_ == nullptr) {
    auto* p = CreateMaybeMessage<::xdisk::XFileInfo>(GetArenaForAllocation());
    _impl_.file_ = p;
  }
  return _impl_.file_;
}
inline ::xdisk::XFileInfo* XFileSlice::mutable_file() {
  ::xdisk::XFileInfo* _msg = _internal_mutable_file();
  // @@protoc_insertion_point(field_mutable:xdisk.XFileSlice.file)
  return _msg;
}
inline void XFileSlice::set_allocated_file(::xdisk::XFileInfo* file) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.file_;
  }
  if (file) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(file);
    if (message_arena != submessage_arena) {
      file = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, file, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.file_ = file;
  // @@protoc_insertion_point(field_set_allocated:xdisk.XFileSlice.file)
}

// int64 size = 2;
inline void XFileSlice::clear_size() {
  _impl_.size_ = int64_t{0};
}
inline int64_t XFileSlice::_internal_size() const {
  return _impl_.size_;
}
inline int64_t XFileSlice::size() const {
  // @@protoc_insertion_point(field_get:xdisk.XFileSlice.size)
  return _internal_size();
}
inline void XFileSlice::_internal_set_size(int64_t value) {
  
  _impl_.size_ = value;
}
inline void XFileSlice::set_size(int64_t value) {
  _internal_set_size(value);
  // @@protoc_insertion_point(field_set:xdisk.XFileSlice.size)
}

// int64 offset = 3;
inline void XFileSlice::clear_offset() {
  _impl_.offset_ = int64_t{0};
}
inline int64_t XFileSlice::_internal_offset() const {
  return _impl_.offset_;
}
inline int64_t XFileSlice::offset() const {
  // @@protoc_insertion_point(field_get:xdisk.XFileSlice.offset)
  return _internal_offset();
}
inline void XFileSlice::_internal_set_offset(int64_t value) {
  
  _impl_.offset_ = value;
}
inline void XFileSlice::set_offset(int64_t value) {
  _internal_set_offset(value);
  // @@protoc_insertion_point(field_set:xdisk.XFileSlice.offset)
}

// bytes md5 = 4;
inline void XFileSlice::clear_md5() {
  _impl_.md5_.ClearToEmpty();
}
inline const std::string& XFileSlice::md5() const {
  // @@protoc_insertion_point(field_get:xdisk.XFileSlice.md5)
  return _internal_md5();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void XFileSlice::set_md5(ArgT0&& arg0, ArgT... args) {
 
 _impl_.md5_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:xdisk.XFileSlice.md5)
}
inline std::string* XFileSlice::mutable_md5() {
  std::string* _s = _internal_mutable_md5();
  // @@protoc_insertion_point(field_mutable:xdisk.XFileSlice.md5)
  return _s;
}
inline const std::string& XFileSlice::_internal_md5() const {
  return _impl_.md5_.Get();
}
inline void XFileSlice::_internal_set_md5(const std::string& value) {
  
  _impl_.md5_.Set(value, GetArenaForAllocation());
}
inline std::string* XFileSlice::_internal_mutable_md5() {
  
  return _impl_.md5_.Mutable(GetArenaForAllocation());
}
inline std::string* XFileSlice::release_md5() {
  // @@protoc_insertion_point(field_release:xdisk.XFileSlice.md5)
  return _impl_.md5_.Release();
}
inline void XFileSlice::set_allocated_md5(std::string* md5) {
  if (md5 != nullptr) {
    
  } else {
    
  }
  _impl_.md5_.SetAllocated(md5, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.md5_.IsDefault()) {
    _impl_.md5_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:xdisk.XFileSlice.md5)
}

// bool is_ok = 5;
inline void XFileSlice::clear_is_ok() {
  _impl_.is_ok_ = false;
}
inline bool XFileSlice::_internal_is_ok() const {
  return _impl_.is_ok_;
}
inline bool XFileSlice::is_ok() const {
  // @@protoc_insertion_point(field_get:xdisk.XFileSlice.is_ok)
  return _internal_is_ok();
}
inline void XFileSlice::_internal_set_is_ok(bool value) {
  
  _impl_.is_ok_ = value;
}
inline void XFileSlice::set_is_ok(bool value) {
  _internal_set_is_ok(value);
  // @@protoc_insertion_point(field_set:xdisk.XFileSlice.is_ok)
}

// -------------------------------------------------------------------

// XFileInfo

// bytes filename = 1;
inline void XFileInfo::clear_filename() {
  _impl_.filename_.ClearToEmpty();
}
inline const std::string& XFileInfo::filename() const {
  // @@protoc_insertion_point(field_get:xdisk.XFileInfo.filename)
  return _internal_filename();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void XFileInfo::set_filename(ArgT0&& arg0, ArgT... args) {
 
 _impl_.filename_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:xdisk.XFileInfo.filename)
}
inline std::string* XFileInfo::mutable_filename() {
  std::string* _s = _internal_mutable_filename();
  // @@protoc_insertion_point(field_mutable:xdisk.XFileInfo.filename)
  return _s;
}
inline const std::string& XFileInfo::_internal_filename() const {
  return _impl_.filename_.Get();
}
inline void XFileInfo::_internal_set_filename(const std::string& value) {
  
  _impl_.filename_.Set(value, GetArenaForAllocation());
}
inline std::string* XFileInfo::_internal_mutable_filename() {
  
  return _impl_.filename_.Mutable(GetArenaForAllocation());
}
inline std::string* XFileInfo::release_filename() {
  // @@protoc_insertion_point(field_release:xdisk.XFileInfo.filename)
  return _impl_.filename_.Release();
}
inline void XFileInfo::set_allocated_filename(std::string* filename) {
  if (filename != nullptr) {
    
  } else {
    
  }
  _impl_.filename_.SetAllocated(filename, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.filename_.IsDefault()) {
    _impl_.filename_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:xdisk.XFileInfo.filename)
}

// bytes filedir = 2;
inline void XFileInfo::clear_filedir() {
  _impl_.filedir_.ClearToEmpty();
}
inline const std::string& XFileInfo::filedir() const {
  // @@protoc_insertion_point(field_get:xdisk.XFileInfo.filedir)
  return _internal_filedir();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void XFileInfo::set_filedir(ArgT0&& arg0, ArgT... args) {
 
 _impl_.filedir_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:xdisk.XFileInfo.filedir)
}
inline std::string* XFileInfo::mutable_filedir() {
  std::string* _s = _internal_mutable_filedir();
  // @@protoc_insertion_point(field_mutable:xdisk.XFileInfo.filedir)
  return _s;
}
inline const std::string& XFileInfo::_internal_filedir() const {
  return _impl_.filedir_.Get();
}
inline void XFileInfo::_internal_set_filedir(const std::string& value) {
  
  _impl_.filedir_.Set(value, GetArenaForAllocation());
}
inline std::string* XFileInfo::_internal_mutable_filedir() {
  
  return _impl_.filedir_.Mutable(GetArenaForAllocation());
}
inline std::string* XFileInfo::release_filedir() {
  // @@protoc_insertion_point(field_release:xdisk.XFileInfo.filedir)
  return _impl_.filedir_.Release();
}
inline void XFileInfo::set_allocated_filedir(std::string* filedir) {
  if (filedir != nullptr) {
    
  } else {
    
  }
  _impl_.filedir_.SetAllocated(filedir, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.filedir_.IsDefault()) {
    _impl_.filedir_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:xdisk.XFileInfo.filedir)
}

// int64 filesize = 3;
inline void XFileInfo::clear_filesize() {
  _impl_.filesize_ = int64_t{0};
}
inline int64_t XFileInfo::_internal_filesize() const {
  return _impl_.filesize_;
}
inline int64_t XFileInfo::filesize() const {
  // @@protoc_insertion_point(field_get:xdisk.XFileInfo.filesize)
  return _internal_filesize();
}
inline void XFileInfo::_internal_set_filesize(int64_t value) {
  
  _impl_.filesize_ = value;
}
inline void XFileInfo::set_filesize(int64_t value) {
  _internal_set_filesize(value);
  // @@protoc_insertion_point(field_set:xdisk.XFileInfo.filesize)
}

// string filetime = 4;
inline void XFileInfo::clear_filetime() {
  _impl_.filetime_.ClearToEmpty();
}
inline const std::string& XFileInfo::filetime() const {
  // @@protoc_insertion_point(field_get:xdisk.XFileInfo.filetime)
  return _internal_filetime();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void XFileInfo::set_filetime(ArgT0&& arg0, ArgT... args) {
 
 _impl_.filetime_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:xdisk.XFileInfo.filetime)
}
inline std::string* XFileInfo::mutable_filetime() {
  std::string* _s = _internal_mutable_filetime();
  // @@protoc_insertion_point(field_mutable:xdisk.XFileInfo.filetime)
  return _s;
}
inline const std::string& XFileInfo::_internal_filetime() const {
  return _impl_.filetime_.Get();
}
inline void XFileInfo::_internal_set_filetime(const std::string& value) {
  
  _impl_.filetime_.Set(value, GetArenaForAllocation());
}
inline std::string* XFileInfo::_internal_mutable_filetime() {
  
  return _impl_.filetime_.Mutable(GetArenaForAllocation());
}
inline std::string* XFileInfo::release_filetime() {
  // @@protoc_insertion_point(field_release:xdisk.XFileInfo.filetime)
  return _impl_.filetime_.Release();
}
inline void XFileInfo::set_allocated_filetime(std::string* filetime) {
  if (filetime != nullptr) {
    
  } else {
    
  }
  _impl_.filetime_.SetAllocated(filetime, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.filetime_.IsDefault()) {
    _impl_.filetime_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:xdisk.XFileInfo.filetime)
}

// bool is_dir = 5;
inline void XFileInfo::clear_is_dir() {
  _impl_.is_dir_ = false;
}
inline bool XFileInfo::_internal_is_dir() const {
  return _impl_.is_dir_;
}
inline bool XFileInfo::is_dir() const {
  // @@protoc_insertion_point(field_get:xdisk.XFileInfo.is_dir)
  return _internal_is_dir();
}
inline void XFileInfo::_internal_set_is_dir(bool value) {
  
  _impl_.is_dir_ = value;
}
inline void XFileInfo::set_is_dir(bool value) {
  _internal_set_is_dir(value);
  // @@protoc_insertion_point(field_set:xdisk.XFileInfo.is_dir)
}

// bytes md5 = 6;
inline void XFileInfo::clear_md5() {
  _impl_.md5_.ClearToEmpty();
}
inline const std::string& XFileInfo::md5() const {
  // @@protoc_insertion_point(field_get:xdisk.XFileInfo.md5)
  return _internal_md5();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void XFileInfo::set_md5(ArgT0&& arg0, ArgT... args) {
 
 _impl_.md5_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:xdisk.XFileInfo.md5)
}
inline std::string* XFileInfo::mutable_md5() {
  std::string* _s = _internal_mutable_md5();
  // @@protoc_insertion_point(field_mutable:xdisk.XFileInfo.md5)
  return _s;
}
inline const std::string& XFileInfo::_internal_md5() const {
  return _impl_.md5_.Get();
}
inline void XFileInfo::_internal_set_md5(const std::string& value) {
  
  _impl_.md5_.Set(value, GetArenaForAllocation());
}
inline std::string* XFileInfo::_internal_mutable_md5() {
  
  return _impl_.md5_.Mutable(GetArenaForAllocation());
}
inline std::string* XFileInfo::release_md5() {
  // @@protoc_insertion_point(field_release:xdisk.XFileInfo.md5)
  return _impl_.md5_.Release();
}
inline void XFileInfo::set_allocated_md5(std::string* md5) {
  if (md5 != nullptr) {
    
  } else {
    
  }
  _impl_.md5_.SetAllocated(md5, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.md5_.IsDefault()) {
    _impl_.md5_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:xdisk.XFileInfo.md5)
}

// bytes local_path = 7;
inline void XFileInfo::clear_local_path() {
  _impl_.local_path_.ClearToEmpty();
}
inline const std::string& XFileInfo::local_path() const {
  // @@protoc_insertion_point(field_get:xdisk.XFileInfo.local_path)
  return _internal_local_path();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void XFileInfo::set_local_path(ArgT0&& arg0, ArgT... args) {
 
 _impl_.local_path_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:xdisk.XFileInfo.local_path)
}
inline std::string* XFileInfo::mutable_local_path() {
  std::string* _s = _internal_mutable_local_path();
  // @@protoc_insertion_point(field_mutable:xdisk.XFileInfo.local_path)
  return _s;
}
inline const std::string& XFileInfo::_internal_local_path() const {
  return _impl_.local_path_.Get();
}
inline void XFileInfo::_internal_set_local_path(const std::string& value) {
  
  _impl_.local_path_.Set(value, GetArenaForAllocation());
}
inline std::string* XFileInfo::_internal_mutable_local_path() {
  
  return _impl_.local_path_.Mutable(GetArenaForAllocation());
}
inline std::string* XFileInfo::release_local_path() {
  // @@protoc_insertion_point(field_release:xdisk.XFileInfo.local_path)
  return _impl_.local_path_.Release();
}
inline void XFileInfo::set_allocated_local_path(std::string* local_path) {
  if (local_path != nullptr) {
    
  } else {
    
  }
  _impl_.local_path_.SetAllocated(local_path, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.local_path_.IsDefault()) {
    _impl_.local_path_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:xdisk.XFileInfo.local_path)
}

// int64 net_size = 8;
inline void XFileInfo::clear_net_size() {
  _impl_.net_size_ = int64_t{0};
}
inline int64_t XFileInfo::_internal_net_size() const {
  return _impl_.net_size_;
}
inline int64_t XFileInfo::net_size() const {
  // @@protoc_insertion_point(field_get:xdisk.XFileInfo.net_size)
  return _internal_net_size();
}
inline void XFileInfo::_internal_set_net_size(int64_t value) {
  
  _impl_.net_size_ = value;
}
inline void XFileInfo::set_net_size(int64_t value) {
  _internal_set_net_size(value);
  // @@protoc_insertion_point(field_set:xdisk.XFileInfo.net_size)
}

// bool is_enc = 9;
inline void XFileInfo::clear_is_enc() {
  _impl_.is_enc_ = false;
}
inline bool XFileInfo::_internal_is_enc() const {
  return _impl_.is_enc_;
}
inline bool XFileInfo::is_enc() const {
  // @@protoc_insertion_point(field_get:xdisk.XFileInfo.is_enc)
  return _internal_is_enc();
}
inline void XFileInfo::_internal_set_is_enc(bool value) {
  
  _impl_.is_enc_ = value;
}
inline void XFileInfo::set_is_enc(bool value) {
  _internal_set_is_enc(value);
  // @@protoc_insertion_point(field_set:xdisk.XFileInfo.is_enc)
}

// int64 ori_size = 10;
inline void XFileInfo::clear_ori_size() {
  _impl_.ori_size_ = int64_t{0};
}
inline int64_t XFileInfo::_internal_ori_size() const {
  return _impl_.ori_size_;
}
inline int64_t XFileInfo::ori_size() const {
  // @@protoc_insertion_point(field_get:xdisk.XFileInfo.ori_size)
  return _internal_ori_size();
}
inline void XFileInfo::_internal_set_ori_size(int64_t value) {
  
  _impl_.ori_size_ = value;
}
inline void XFileInfo::set_ori_size(int64_t value) {
  _internal_set_ori_size(value);
  // @@protoc_insertion_point(field_set:xdisk.XFileInfo.ori_size)
}

// bytes password = 11;
inline void XFileInfo::clear_password() {
  _impl_.password_.ClearToEmpty();
}
inline const std::string& XFileInfo::password() const {
  // @@protoc_insertion_point(field_get:xdisk.XFileInfo.password)
  return _internal_password();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void XFileInfo::set_password(ArgT0&& arg0, ArgT... args) {
 
 _impl_.password_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:xdisk.XFileInfo.password)
}
inline std::string* XFileInfo::mutable_password() {
  std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:xdisk.XFileInfo.password)
  return _s;
}
inline const std::string& XFileInfo::_internal_password() const {
  return _impl_.password_.Get();
}
inline void XFileInfo::_internal_set_password(const std::string& value) {
  
  _impl_.password_.Set(value, GetArenaForAllocation());
}
inline std::string* XFileInfo::_internal_mutable_password() {
  
  return _impl_.password_.Mutable(GetArenaForAllocation());
}
inline std::string* XFileInfo::release_password() {
  // @@protoc_insertion_point(field_release:xdisk.XFileInfo.password)
  return _impl_.password_.Release();
}
inline void XFileInfo::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  _impl_.password_.SetAllocated(password, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.password_.IsDefault()) {
    _impl_.password_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:xdisk.XFileInfo.password)
}

// -------------------------------------------------------------------

// XFileInfoList

// repeated .xdisk.XFileInfo files = 4;
inline int XFileInfoList::_internal_files_size() const {
  return _impl_.files_.size();
}
inline int XFileInfoList::files_size() const {
  return _internal_files_size();
}
inline void XFileInfoList::clear_files() {
  _impl_.files_.Clear();
}
inline ::xdisk::XFileInfo* XFileInfoList::mutable_files(int index) {
  // @@protoc_insertion_point(field_mutable:xdisk.XFileInfoList.files)
  return _impl_.files_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::xdisk::XFileInfo >*
XFileInfoList::mutable_files() {
  // @@protoc_insertion_point(field_mutable_list:xdisk.XFileInfoList.files)
  return &_impl_.files_;
}
inline const ::xdisk::XFileInfo& XFileInfoList::_internal_files(int index) const {
  return _impl_.files_.Get(index);
}
inline const ::xdisk::XFileInfo& XFileInfoList::files(int index) const {
  // @@protoc_insertion_point(field_get:xdisk.XFileInfoList.files)
  return _internal_files(index);
}
inline ::xdisk::XFileInfo* XFileInfoList::_internal_add_files() {
  return _impl_.files_.Add();
}
inline ::xdisk::XFileInfo* XFileInfoList::add_files() {
  ::xdisk::XFileInfo* _add = _internal_add_files();
  // @@protoc_insertion_point(field_add:xdisk.XFileInfoList.files)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::xdisk::XFileInfo >&
XFileInfoList::files() const {
  // @@protoc_insertion_point(field_list:xdisk.XFileInfoList.files)
  return _impl_.files_;
}

// -------------------------------------------------------------------

// XFileTask

// int32 index = 1;
inline void XFileTask::clear_index() {
  _impl_.index_ = 0;
}
inline int32_t XFileTask::_internal_index() const {
  return _impl_.index_;
}
inline int32_t XFileTask::index() const {
  // @@protoc_insertion_point(field_get:xdisk.XFileTask.index)
  return _internal_index();
}
inline void XFileTask::_internal_set_index(int32_t value) {
  
  _impl_.index_ = value;
}
inline void XFileTask::set_index(int32_t value) {
  _internal_set_index(value);
  // @@protoc_insertion_point(field_set:xdisk.XFileTask.index)
}

// string tasktime = 6;
inline void XFileTask::clear_tasktime() {
  _impl_.tasktime_.ClearToEmpty();
}
inline const std::string& XFileTask::tasktime() const {
  // @@protoc_insertion_point(field_get:xdisk.XFileTask.tasktime)
  return _internal_tasktime();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void XFileTask::set_tasktime(ArgT0&& arg0, ArgT... args) {
 
 _impl_.tasktime_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:xdisk.XFileTask.tasktime)
}
inline std::string* XFileTask::mutable_tasktime() {
  std::string* _s = _internal_mutable_tasktime();
  // @@protoc_insertion_point(field_mutable:xdisk.XFileTask.tasktime)
  return _s;
}
inline const std::string& XFileTask::_internal_tasktime() const {
  return _impl_.tasktime_.Get();
}
inline void XFileTask::_internal_set_tasktime(const std::string& value) {
  
  _impl_.tasktime_.Set(value, GetArenaForAllocation());
}
inline std::string* XFileTask::_internal_mutable_tasktime() {
  
  return _impl_.tasktime_.Mutable(GetArenaForAllocation());
}
inline std::string* XFileTask::release_tasktime() {
  // @@protoc_insertion_point(field_release:xdisk.XFileTask.tasktime)
  return _impl_.tasktime_.Release();
}
inline void XFileTask::set_allocated_tasktime(std::string* tasktime) {
  if (tasktime != nullptr) {
    
  } else {
    
  }
  _impl_.tasktime_.SetAllocated(tasktime, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.tasktime_.IsDefault()) {
    _impl_.tasktime_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:xdisk.XFileTask.tasktime)
}

// bool is_complete = 7;
inline void XFileTask::clear_is_complete() {
  _impl_.is_complete_ = false;
}
inline bool XFileTask::_internal_is_complete() const {
  return _impl_.is_complete_;
}
inline bool XFileTask::is_complete() const {
  // @@protoc_insertion_point(field_get:xdisk.XFileTask.is_complete)
  return _internal_is_complete();
}
inline void XFileTask::_internal_set_is_complete(bool value) {
  
  _impl_.is_complete_ = value;
}
inline void XFileTask::set_is_complete(bool value) {
  _internal_set_is_complete(value);
  // @@protoc_insertion_point(field_set:xdisk.XFileTask.is_complete)
}

// bool is_sec = 8;
inline void XFileTask::clear_is_sec() {
  _impl_.is_sec_ = false;
}
inline bool XFileTask::_internal_is_sec() const {
  return _impl_.is_sec_;
}
inline bool XFileTask::is_sec() const {
  // @@protoc_insertion_point(field_get:xdisk.XFileTask.is_sec)
  return _internal_is_sec();
}
inline void XFileTask::_internal_set_is_sec(bool value) {
  
  _impl_.is_sec_ = value;
}
inline void XFileTask::set_is_sec(bool value) {
  _internal_set_is_sec(value);
  // @@protoc_insertion_point(field_set:xdisk.XFileTask.is_sec)
}

// .xdisk.XFileInfo file = 9;
inline bool XFileTask::_internal_has_file() const {
  return this != internal_default_instance() && _impl_.file_ != nullptr;
}
inline bool XFileTask::has_file() const {
  return _internal_has_file();
}
inline void XFileTask::clear_file() {
  if (GetArenaForAllocation() == nullptr && _impl_.file_ != nullptr) {
    delete _impl_.file_;
  }
  _impl_.file_ = nullptr;
}
inline const ::xdisk::XFileInfo& XFileTask::_internal_file() const {
  const ::xdisk::XFileInfo* p = _impl_.file_;
  return p != nullptr ? *p : reinterpret_cast<const ::xdisk::XFileInfo&>(
      ::xdisk::_XFileInfo_default_instance_);
}
inline const ::xdisk::XFileInfo& XFileTask::file() const {
  // @@protoc_insertion_point(field_get:xdisk.XFileTask.file)
  return _internal_file();
}
inline void XFileTask::unsafe_arena_set_allocated_file(
    ::xdisk::XFileInfo* file) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.file_);
  }
  _impl_.file_ = file;
  if (file) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:xdisk.XFileTask.file)
}
inline ::xdisk::XFileInfo* XFileTask::release_file() {
  
  ::xdisk::XFileInfo* temp = _impl_.file_;
  _impl_.file_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::xdisk::XFileInfo* XFileTask::unsafe_arena_release_file() {
  // @@protoc_insertion_point(field_release:xdisk.XFileTask.file)
  
  ::xdisk::XFileInfo* temp = _impl_.file_;
  _impl_.file_ = nullptr;
  return temp;
}
inline ::xdisk::XFileInfo* XFileTask::_internal_mutable_file() {
  
  if (_impl_.file_ == nullptr) {
    auto* p = CreateMaybeMessage<::xdisk::XFileInfo>(GetArenaForAllocation());
    _impl_.file_ = p;
  }
  return _impl_.file_;
}
inline ::xdisk::XFileInfo* XFileTask::mutable_file() {
  ::xdisk::XFileInfo* _msg = _internal_mutable_file();
  // @@protoc_insertion_point(field_mutable:xdisk.XFileTask.file)
  return _msg;
}
inline void XFileTask::set_allocated_file(::xdisk::XFileInfo* file) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.file_;
  }
  if (file) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(file);
    if (message_arena != submessage_arena) {
      file = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, file, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.file_ = file;
  // @@protoc_insertion_point(field_set_allocated:xdisk.XFileTask.file)
}

// bool is_upload = 10;
inline void XFileTask::clear_is_upload() {
  _impl_.is_upload_ = false;
}
inline bool XFileTask::_internal_is_upload() const {
  return _impl_.is_upload_;
}
inline bool XFileTask::is_upload() const {
  // @@protoc_insertion_point(field_get:xdisk.XFileTask.is_upload)
  return _internal_is_upload();
}
inline void XFileTask::_internal_set_is_upload(bool value) {
  
  _impl_.is_upload_ = value;
}
inline void XFileTask::set_is_upload(bool value) {
  _internal_set_is_upload(value);
  // @@protoc_insertion_point(field_set:xdisk.XFileTask.is_upload)
}

// -------------------------------------------------------------------

// XFileTaskList

// repeated .xdisk.XFileTask uploads = 1;
inline int XFileTaskList::_internal_uploads_size() const {
  return _impl_.uploads_.size();
}
inline int XFileTaskList::uploads_size() const {
  return _internal_uploads_size();
}
inline void XFileTaskList::clear_uploads() {
  _impl_.uploads_.Clear();
}
inline ::xdisk::XFileTask* XFileTaskList::mutable_uploads(int index) {
  // @@protoc_insertion_point(field_mutable:xdisk.XFileTaskList.uploads)
  return _impl_.uploads_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::xdisk::XFileTask >*
XFileTaskList::mutable_uploads() {
  // @@protoc_insertion_point(field_mutable_list:xdisk.XFileTaskList.uploads)
  return &_impl_.uploads_;
}
inline const ::xdisk::XFileTask& XFileTaskList::_internal_uploads(int index) const {
  return _impl_.uploads_.Get(index);
}
inline const ::xdisk::XFileTask& XFileTaskList::uploads(int index) const {
  // @@protoc_insertion_point(field_get:xdisk.XFileTaskList.uploads)
  return _internal_uploads(index);
}
inline ::xdisk::XFileTask* XFileTaskList::_internal_add_uploads() {
  return _impl_.uploads_.Add();
}
inline ::xdisk::XFileTask* XFileTaskList::add_uploads() {
  ::xdisk::XFileTask* _add = _internal_add_uploads();
  // @@protoc_insertion_point(field_add:xdisk.XFileTaskList.uploads)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::xdisk::XFileTask >&
XFileTaskList::uploads() const {
  // @@protoc_insertion_point(field_list:xdisk.XFileTaskList.uploads)
  return _impl_.uploads_;
}

// repeated .xdisk.XFileTask downloads = 2;
inline int XFileTaskList::_internal_downloads_size() const {
  return _impl_.downloads_.size();
}
inline int XFileTaskList::downloads_size() const {
  return _internal_downloads_size();
}
inline void XFileTaskList::clear_downloads() {
  _impl_.downloads_.Clear();
}
inline ::xdisk::XFileTask* XFileTaskList::mutable_downloads(int index) {
  // @@protoc_insertion_point(field_mutable:xdisk.XFileTaskList.downloads)
  return _impl_.downloads_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::xdisk::XFileTask >*
XFileTaskList::mutable_downloads() {
  // @@protoc_insertion_point(field_mutable_list:xdisk.XFileTaskList.downloads)
  return &_impl_.downloads_;
}
inline const ::xdisk::XFileTask& XFileTaskList::_internal_downloads(int index) const {
  return _impl_.downloads_.Get(index);
}
inline const ::xdisk::XFileTask& XFileTaskList::downloads(int index) const {
  // @@protoc_insertion_point(field_get:xdisk.XFileTaskList.downloads)
  return _internal_downloads(index);
}
inline ::xdisk::XFileTask* XFileTaskList::_internal_add_downloads() {
  return _impl_.downloads_.Add();
}
inline ::xdisk::XFileTask* XFileTaskList::add_downloads() {
  ::xdisk::XFileTask* _add = _internal_add_downloads();
  // @@protoc_insertion_point(field_add:xdisk.XFileTaskList.downloads)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::xdisk::XFileTask >&
XFileTaskList::downloads() const {
  // @@protoc_insertion_point(field_list:xdisk.XFileTaskList.downloads)
  return _impl_.downloads_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace xdisk

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::xdisk::XFileMsgType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::xdisk::XFileMsgType>() {
  return ::xdisk::XFileMsgType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_xms_5fdisk_5fclient_5fgui_2eproto
