// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xms_disk_client_gui.proto

#include "xms_disk_client_gui.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace xdisk {
PROTOBUF_CONSTEXPR XDiskInfo::XDiskInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.avail_)*/int64_t{0}
  , /*decltype(_impl_.total_)*/int64_t{0}
  , /*decltype(_impl_.free_)*/int64_t{0}
  , /*decltype(_impl_.dir_size_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct XDiskInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR XDiskInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~XDiskInfoDefaultTypeInternal() {}
  union {
    XDiskInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 XDiskInfoDefaultTypeInternal _XDiskInfo_default_instance_;
PROTOBUF_CONSTEXPR XGetDirReq::XGetDirReq(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.root_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct XGetDirReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR XGetDirReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~XGetDirReqDefaultTypeInternal() {}
  union {
    XGetDirReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 XGetDirReqDefaultTypeInternal _XGetDirReq_default_instance_;
PROTOBUF_CONSTEXPR XFileSlice::XFileSlice(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.md5_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.file_)*/nullptr
  , /*decltype(_impl_.size_)*/int64_t{0}
  , /*decltype(_impl_.offset_)*/int64_t{0}
  , /*decltype(_impl_.is_ok_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct XFileSliceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR XFileSliceDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~XFileSliceDefaultTypeInternal() {}
  union {
    XFileSlice _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 XFileSliceDefaultTypeInternal _XFileSlice_default_instance_;
PROTOBUF_CONSTEXPR XFileInfo::XFileInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.filename_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.filedir_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.filetime_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.md5_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.local_path_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.password_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.filesize_)*/int64_t{0}
  , /*decltype(_impl_.net_size_)*/int64_t{0}
  , /*decltype(_impl_.ori_size_)*/int64_t{0}
  , /*decltype(_impl_.is_dir_)*/false
  , /*decltype(_impl_.is_enc_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct XFileInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR XFileInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~XFileInfoDefaultTypeInternal() {}
  union {
    XFileInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 XFileInfoDefaultTypeInternal _XFileInfo_default_instance_;
PROTOBUF_CONSTEXPR XFileInfoList::XFileInfoList(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.files_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct XFileInfoListDefaultTypeInternal {
  PROTOBUF_CONSTEXPR XFileInfoListDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~XFileInfoListDefaultTypeInternal() {}
  union {
    XFileInfoList _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 XFileInfoListDefaultTypeInternal _XFileInfoList_default_instance_;
PROTOBUF_CONSTEXPR XFileTask::XFileTask(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.tasktime_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.file_)*/nullptr
  , /*decltype(_impl_.index_)*/0
  , /*decltype(_impl_.is_complete_)*/false
  , /*decltype(_impl_.is_sec_)*/false
  , /*decltype(_impl_.is_upload_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct XFileTaskDefaultTypeInternal {
  PROTOBUF_CONSTEXPR XFileTaskDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~XFileTaskDefaultTypeInternal() {}
  union {
    XFileTask _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 XFileTaskDefaultTypeInternal _XFileTask_default_instance_;
PROTOBUF_CONSTEXPR XFileTaskList::XFileTaskList(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.uploads_)*/{}
  , /*decltype(_impl_.downloads_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct XFileTaskListDefaultTypeInternal {
  PROTOBUF_CONSTEXPR XFileTaskListDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~XFileTaskListDefaultTypeInternal() {}
  union {
    XFileTaskList _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 XFileTaskListDefaultTypeInternal _XFileTaskList_default_instance_;
}  // namespace xdisk
static ::_pb::Metadata file_level_metadata_xms_5fdisk_5fclient_5fgui_2eproto[7];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_xms_5fdisk_5fclient_5fgui_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_xms_5fdisk_5fclient_5fgui_2eproto = nullptr;

const uint32_t TableStruct_xms_5fdisk_5fclient_5fgui_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::xdisk::XDiskInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::xdisk::XDiskInfo, _impl_.avail_),
  PROTOBUF_FIELD_OFFSET(::xdisk::XDiskInfo, _impl_.total_),
  PROTOBUF_FIELD_OFFSET(::xdisk::XDiskInfo, _impl_.free_),
  PROTOBUF_FIELD_OFFSET(::xdisk::XDiskInfo, _impl_.dir_size_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::xdisk::XGetDirReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::xdisk::XGetDirReq, _impl_.root_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileSlice, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileSlice, _impl_.file_),
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileSlice, _impl_.size_),
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileSlice, _impl_.offset_),
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileSlice, _impl_.md5_),
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileSlice, _impl_.is_ok_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileInfo, _impl_.filename_),
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileInfo, _impl_.filedir_),
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileInfo, _impl_.filesize_),
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileInfo, _impl_.filetime_),
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileInfo, _impl_.is_dir_),
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileInfo, _impl_.md5_),
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileInfo, _impl_.local_path_),
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileInfo, _impl_.net_size_),
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileInfo, _impl_.is_enc_),
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileInfo, _impl_.ori_size_),
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileInfo, _impl_.password_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileInfoList, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileInfoList, _impl_.files_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileTask, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileTask, _impl_.index_),
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileTask, _impl_.tasktime_),
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileTask, _impl_.is_complete_),
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileTask, _impl_.is_sec_),
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileTask, _impl_.file_),
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileTask, _impl_.is_upload_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileTaskList, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileTaskList, _impl_.uploads_),
  PROTOBUF_FIELD_OFFSET(::xdisk::XFileTaskList, _impl_.downloads_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::xdisk::XDiskInfo)},
  { 10, -1, -1, sizeof(::xdisk::XGetDirReq)},
  { 17, -1, -1, sizeof(::xdisk::XFileSlice)},
  { 28, -1, -1, sizeof(::xdisk::XFileInfo)},
  { 45, -1, -1, sizeof(::xdisk::XFileInfoList)},
  { 52, -1, -1, sizeof(::xdisk::XFileTask)},
  { 64, -1, -1, sizeof(::xdisk::XFileTaskList)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::xdisk::_XDiskInfo_default_instance_._instance,
  &::xdisk::_XGetDirReq_default_instance_._instance,
  &::xdisk::_XFileSlice_default_instance_._instance,
  &::xdisk::_XFileInfo_default_instance_._instance,
  &::xdisk::_XFileInfoList_default_instance_._instance,
  &::xdisk::_XFileTask_default_instance_._instance,
  &::xdisk::_XFileTaskList_default_instance_._instance,
};

const char descriptor_table_protodef_xms_5fdisk_5fclient_5fgui_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\031xms_disk_client_gui.proto\022\005xdisk\"I\n\tXD"
  "iskInfo\022\r\n\005avail\030\001 \001(\003\022\r\n\005total\030\002 \001(\003\022\014\n"
  "\004free\030\003 \001(\003\022\020\n\010dir_size\030\004 \001(\003\"\032\n\nXGetDir"
  "Req\022\014\n\004root\030\001 \001(\014\"f\n\nXFileSlice\022\036\n\004file\030"
  "\001 \001(\0132\020.xdisk.XFileInfo\022\014\n\004size\030\002 \001(\003\022\016\n"
  "\006offset\030\003 \001(\003\022\013\n\003md5\030\004 \001(\014\022\r\n\005is_ok\030\005 \001("
  "\010\"\311\001\n\tXFileInfo\022\020\n\010filename\030\001 \001(\014\022\017\n\007fil"
  "edir\030\002 \001(\014\022\020\n\010filesize\030\003 \001(\003\022\020\n\010filetime"
  "\030\004 \001(\t\022\016\n\006is_dir\030\005 \001(\010\022\013\n\003md5\030\006 \001(\014\022\022\n\nl"
  "ocal_path\030\007 \001(\014\022\020\n\010net_size\030\010 \001(\003\022\016\n\006is_"
  "enc\030\t \001(\010\022\020\n\010ori_size\030\n \001(\003\022\020\n\010password\030"
  "\013 \001(\014\"0\n\rXFileInfoList\022\037\n\005files\030\004 \003(\0132\020."
  "xdisk.XFileInfo\"\204\001\n\tXFileTask\022\r\n\005index\030\001"
  " \001(\005\022\020\n\010tasktime\030\006 \001(\t\022\023\n\013is_complete\030\007 "
  "\001(\010\022\016\n\006is_sec\030\010 \001(\010\022\036\n\004file\030\t \001(\0132\020.xdis"
  "k.XFileInfo\022\021\n\tis_upload\030\n \001(\010\"W\n\rXFileT"
  "askList\022!\n\007uploads\030\001 \003(\0132\020.xdisk.XFileTa"
  "sk\022#\n\tdownloads\030\002 \003(\0132\020.xdisk.XFileTask*"
  "\314\003\n\014XFileMsgType\022\021\n\rFILE_MSG_NONE\020\000\022\020\n\013G"
  "ET_DIR_REQ\020\351\007\022\020\n\013GET_DIR_RES\020\352\007\022\024\n\017UPLOA"
  "D_FILE_REQ\020\353\007\022\024\n\017UPLOAD_FILE_RES\020\354\007\022\023\n\016S"
  "END_SLICE_REQ\020\355\007\022\023\n\016SEND_SLICE_RES\020\357\007\022\030\n"
  "\023UPLOAD_FILE_END_REQ\020\360\007\022\030\n\023UPLOAD_FILE_E"
  "ND_RES\020\361\007\022\026\n\021DOWNLOAD_FILE_REQ\020\362\007\022\026\n\021DOW"
  "NLOAD_FILE_RES\020\363\007\022\031\n\024DOWNLOAD_FILE_BEGTI"
  "N\020\234N\022\027\n\022DOWNLOAD_SLICE_REQ\020\364\007\022\027\n\022DOWNLOA"
  "D_SLICE_RES\020\365\007\022\024\n\017DELETE_FILE_REQ\020\366\007\022\024\n\017"
  "DELETE_FILE_RES\020\367\007\022\020\n\013NEW_DIR_REQ\020\370\007\022\020\n\013"
  "NEW_DIR_RES\020\371\007\022\026\n\021GET_DISK_INFO_REQ\020\372\007\022\026"
  "\n\021GET_DISK_INFO_RES\020\373\007b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_xms_5fdisk_5fclient_5fgui_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_xms_5fdisk_5fclient_5fgui_2eproto = {
    false, false, 1190, descriptor_table_protodef_xms_5fdisk_5fclient_5fgui_2eproto,
    "xms_disk_client_gui.proto",
    &descriptor_table_xms_5fdisk_5fclient_5fgui_2eproto_once, nullptr, 0, 7,
    schemas, file_default_instances, TableStruct_xms_5fdisk_5fclient_5fgui_2eproto::offsets,
    file_level_metadata_xms_5fdisk_5fclient_5fgui_2eproto, file_level_enum_descriptors_xms_5fdisk_5fclient_5fgui_2eproto,
    file_level_service_descriptors_xms_5fdisk_5fclient_5fgui_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_xms_5fdisk_5fclient_5fgui_2eproto_getter() {
  return &descriptor_table_xms_5fdisk_5fclient_5fgui_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_xms_5fdisk_5fclient_5fgui_2eproto(&descriptor_table_xms_5fdisk_5fclient_5fgui_2eproto);
namespace xdisk {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* XFileMsgType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_xms_5fdisk_5fclient_5fgui_2eproto);
  return file_level_enum_descriptors_xms_5fdisk_5fclient_5fgui_2eproto[0];
}
bool XFileMsgType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1001:
    case 1002:
    case 1003:
    case 1004:
    case 1005:
    case 1007:
    case 1008:
    case 1009:
    case 1010:
    case 1011:
    case 1012:
    case 1013:
    case 1014:
    case 1015:
    case 1016:
    case 1017:
    case 1018:
    case 1019:
    case 10012:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class XDiskInfo::_Internal {
 public:
};

XDiskInfo::XDiskInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:xdisk.XDiskInfo)
}
XDiskInfo::XDiskInfo(const XDiskInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  XDiskInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.avail_){}
    , decltype(_impl_.total_){}
    , decltype(_impl_.free_){}
    , decltype(_impl_.dir_size_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.avail_, &from._impl_.avail_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.dir_size_) -
    reinterpret_cast<char*>(&_impl_.avail_)) + sizeof(_impl_.dir_size_));
  // @@protoc_insertion_point(copy_constructor:xdisk.XDiskInfo)
}

inline void XDiskInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.avail_){int64_t{0}}
    , decltype(_impl_.total_){int64_t{0}}
    , decltype(_impl_.free_){int64_t{0}}
    , decltype(_impl_.dir_size_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

XDiskInfo::~XDiskInfo() {
  // @@protoc_insertion_point(destructor:xdisk.XDiskInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void XDiskInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void XDiskInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void XDiskInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:xdisk.XDiskInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.avail_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.dir_size_) -
      reinterpret_cast<char*>(&_impl_.avail_)) + sizeof(_impl_.dir_size_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* XDiskInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 avail = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.avail_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 total = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.total_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 free = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.free_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 dir_size = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.dir_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* XDiskInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:xdisk.XDiskInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 avail = 1;
  if (this->_internal_avail() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_avail(), target);
  }

  // int64 total = 2;
  if (this->_internal_total() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_total(), target);
  }

  // int64 free = 3;
  if (this->_internal_free() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_free(), target);
  }

  // int64 dir_size = 4;
  if (this->_internal_dir_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(4, this->_internal_dir_size(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:xdisk.XDiskInfo)
  return target;
}

size_t XDiskInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:xdisk.XDiskInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 avail = 1;
  if (this->_internal_avail() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_avail());
  }

  // int64 total = 2;
  if (this->_internal_total() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_total());
  }

  // int64 free = 3;
  if (this->_internal_free() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_free());
  }

  // int64 dir_size = 4;
  if (this->_internal_dir_size() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_dir_size());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData XDiskInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    XDiskInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*XDiskInfo::GetClassData() const { return &_class_data_; }


void XDiskInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<XDiskInfo*>(&to_msg);
  auto& from = static_cast<const XDiskInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:xdisk.XDiskInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_avail() != 0) {
    _this->_internal_set_avail(from._internal_avail());
  }
  if (from._internal_total() != 0) {
    _this->_internal_set_total(from._internal_total());
  }
  if (from._internal_free() != 0) {
    _this->_internal_set_free(from._internal_free());
  }
  if (from._internal_dir_size() != 0) {
    _this->_internal_set_dir_size(from._internal_dir_size());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void XDiskInfo::CopyFrom(const XDiskInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xdisk.XDiskInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool XDiskInfo::IsInitialized() const {
  return true;
}

void XDiskInfo::InternalSwap(XDiskInfo* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(XDiskInfo, _impl_.dir_size_)
      + sizeof(XDiskInfo::_impl_.dir_size_)
      - PROTOBUF_FIELD_OFFSET(XDiskInfo, _impl_.avail_)>(
          reinterpret_cast<char*>(&_impl_.avail_),
          reinterpret_cast<char*>(&other->_impl_.avail_));
}

::PROTOBUF_NAMESPACE_ID::Metadata XDiskInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_xms_5fdisk_5fclient_5fgui_2eproto_getter, &descriptor_table_xms_5fdisk_5fclient_5fgui_2eproto_once,
      file_level_metadata_xms_5fdisk_5fclient_5fgui_2eproto[0]);
}

// ===================================================================

class XGetDirReq::_Internal {
 public:
};

XGetDirReq::XGetDirReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:xdisk.XGetDirReq)
}
XGetDirReq::XGetDirReq(const XGetDirReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  XGetDirReq* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.root_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.root_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.root_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_root().empty()) {
    _this->_impl_.root_.Set(from._internal_root(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:xdisk.XGetDirReq)
}

inline void XGetDirReq::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.root_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.root_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.root_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

XGetDirReq::~XGetDirReq() {
  // @@protoc_insertion_point(destructor:xdisk.XGetDirReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void XGetDirReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.root_.Destroy();
}

void XGetDirReq::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void XGetDirReq::Clear() {
// @@protoc_insertion_point(message_clear_start:xdisk.XGetDirReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.root_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* XGetDirReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes root = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_root();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* XGetDirReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:xdisk.XGetDirReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes root = 1;
  if (!this->_internal_root().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_root(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:xdisk.XGetDirReq)
  return target;
}

size_t XGetDirReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:xdisk.XGetDirReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes root = 1;
  if (!this->_internal_root().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_root());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData XGetDirReq::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    XGetDirReq::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*XGetDirReq::GetClassData() const { return &_class_data_; }


void XGetDirReq::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<XGetDirReq*>(&to_msg);
  auto& from = static_cast<const XGetDirReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:xdisk.XGetDirReq)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_root().empty()) {
    _this->_internal_set_root(from._internal_root());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void XGetDirReq::CopyFrom(const XGetDirReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xdisk.XGetDirReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool XGetDirReq::IsInitialized() const {
  return true;
}

void XGetDirReq::InternalSwap(XGetDirReq* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.root_, lhs_arena,
      &other->_impl_.root_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata XGetDirReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_xms_5fdisk_5fclient_5fgui_2eproto_getter, &descriptor_table_xms_5fdisk_5fclient_5fgui_2eproto_once,
      file_level_metadata_xms_5fdisk_5fclient_5fgui_2eproto[1]);
}

// ===================================================================

class XFileSlice::_Internal {
 public:
  static const ::xdisk::XFileInfo& file(const XFileSlice* msg);
};

const ::xdisk::XFileInfo&
XFileSlice::_Internal::file(const XFileSlice* msg) {
  return *msg->_impl_.file_;
}
XFileSlice::XFileSlice(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:xdisk.XFileSlice)
}
XFileSlice::XFileSlice(const XFileSlice& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  XFileSlice* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.md5_){}
    , decltype(_impl_.file_){nullptr}
    , decltype(_impl_.size_){}
    , decltype(_impl_.offset_){}
    , decltype(_impl_.is_ok_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.md5_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.md5_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_md5().empty()) {
    _this->_impl_.md5_.Set(from._internal_md5(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_file()) {
    _this->_impl_.file_ = new ::xdisk::XFileInfo(*from._impl_.file_);
  }
  ::memcpy(&_impl_.size_, &from._impl_.size_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.is_ok_) -
    reinterpret_cast<char*>(&_impl_.size_)) + sizeof(_impl_.is_ok_));
  // @@protoc_insertion_point(copy_constructor:xdisk.XFileSlice)
}

inline void XFileSlice::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.md5_){}
    , decltype(_impl_.file_){nullptr}
    , decltype(_impl_.size_){int64_t{0}}
    , decltype(_impl_.offset_){int64_t{0}}
    , decltype(_impl_.is_ok_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.md5_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.md5_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

XFileSlice::~XFileSlice() {
  // @@protoc_insertion_point(destructor:xdisk.XFileSlice)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void XFileSlice::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.md5_.Destroy();
  if (this != internal_default_instance()) delete _impl_.file_;
}

void XFileSlice::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void XFileSlice::Clear() {
// @@protoc_insertion_point(message_clear_start:xdisk.XFileSlice)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.md5_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.file_ != nullptr) {
    delete _impl_.file_;
  }
  _impl_.file_ = nullptr;
  ::memset(&_impl_.size_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.is_ok_) -
      reinterpret_cast<char*>(&_impl_.size_)) + sizeof(_impl_.is_ok_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* XFileSlice::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .xdisk.XFileInfo file = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_file(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 size = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 offset = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.offset_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes md5 = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_md5();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool is_ok = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.is_ok_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* XFileSlice::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:xdisk.XFileSlice)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .xdisk.XFileInfo file = 1;
  if (this->_internal_has_file()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::file(this),
        _Internal::file(this).GetCachedSize(), target, stream);
  }

  // int64 size = 2;
  if (this->_internal_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_size(), target);
  }

  // int64 offset = 3;
  if (this->_internal_offset() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_offset(), target);
  }

  // bytes md5 = 4;
  if (!this->_internal_md5().empty()) {
    target = stream->WriteBytesMaybeAliased(
        4, this->_internal_md5(), target);
  }

  // bool is_ok = 5;
  if (this->_internal_is_ok() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(5, this->_internal_is_ok(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:xdisk.XFileSlice)
  return target;
}

size_t XFileSlice::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:xdisk.XFileSlice)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes md5 = 4;
  if (!this->_internal_md5().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_md5());
  }

  // .xdisk.XFileInfo file = 1;
  if (this->_internal_has_file()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.file_);
  }

  // int64 size = 2;
  if (this->_internal_size() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_size());
  }

  // int64 offset = 3;
  if (this->_internal_offset() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_offset());
  }

  // bool is_ok = 5;
  if (this->_internal_is_ok() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData XFileSlice::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    XFileSlice::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*XFileSlice::GetClassData() const { return &_class_data_; }


void XFileSlice::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<XFileSlice*>(&to_msg);
  auto& from = static_cast<const XFileSlice&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:xdisk.XFileSlice)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_md5().empty()) {
    _this->_internal_set_md5(from._internal_md5());
  }
  if (from._internal_has_file()) {
    _this->_internal_mutable_file()->::xdisk::XFileInfo::MergeFrom(
        from._internal_file());
  }
  if (from._internal_size() != 0) {
    _this->_internal_set_size(from._internal_size());
  }
  if (from._internal_offset() != 0) {
    _this->_internal_set_offset(from._internal_offset());
  }
  if (from._internal_is_ok() != 0) {
    _this->_internal_set_is_ok(from._internal_is_ok());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void XFileSlice::CopyFrom(const XFileSlice& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xdisk.XFileSlice)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool XFileSlice::IsInitialized() const {
  return true;
}

void XFileSlice::InternalSwap(XFileSlice* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.md5_, lhs_arena,
      &other->_impl_.md5_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(XFileSlice, _impl_.is_ok_)
      + sizeof(XFileSlice::_impl_.is_ok_)
      - PROTOBUF_FIELD_OFFSET(XFileSlice, _impl_.file_)>(
          reinterpret_cast<char*>(&_impl_.file_),
          reinterpret_cast<char*>(&other->_impl_.file_));
}

::PROTOBUF_NAMESPACE_ID::Metadata XFileSlice::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_xms_5fdisk_5fclient_5fgui_2eproto_getter, &descriptor_table_xms_5fdisk_5fclient_5fgui_2eproto_once,
      file_level_metadata_xms_5fdisk_5fclient_5fgui_2eproto[2]);
}

// ===================================================================

class XFileInfo::_Internal {
 public:
};

XFileInfo::XFileInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:xdisk.XFileInfo)
}
XFileInfo::XFileInfo(const XFileInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  XFileInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.filename_){}
    , decltype(_impl_.filedir_){}
    , decltype(_impl_.filetime_){}
    , decltype(_impl_.md5_){}
    , decltype(_impl_.local_path_){}
    , decltype(_impl_.password_){}
    , decltype(_impl_.filesize_){}
    , decltype(_impl_.net_size_){}
    , decltype(_impl_.ori_size_){}
    , decltype(_impl_.is_dir_){}
    , decltype(_impl_.is_enc_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.filename_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.filename_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_filename().empty()) {
    _this->_impl_.filename_.Set(from._internal_filename(), 
      _this->GetArenaForAllocation());
  }
  _impl_.filedir_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.filedir_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_filedir().empty()) {
    _this->_impl_.filedir_.Set(from._internal_filedir(), 
      _this->GetArenaForAllocation());
  }
  _impl_.filetime_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.filetime_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_filetime().empty()) {
    _this->_impl_.filetime_.Set(from._internal_filetime(), 
      _this->GetArenaForAllocation());
  }
  _impl_.md5_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.md5_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_md5().empty()) {
    _this->_impl_.md5_.Set(from._internal_md5(), 
      _this->GetArenaForAllocation());
  }
  _impl_.local_path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.local_path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_local_path().empty()) {
    _this->_impl_.local_path_.Set(from._internal_local_path(), 
      _this->GetArenaForAllocation());
  }
  _impl_.password_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.password_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_password().empty()) {
    _this->_impl_.password_.Set(from._internal_password(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.filesize_, &from._impl_.filesize_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.is_enc_) -
    reinterpret_cast<char*>(&_impl_.filesize_)) + sizeof(_impl_.is_enc_));
  // @@protoc_insertion_point(copy_constructor:xdisk.XFileInfo)
}

inline void XFileInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.filename_){}
    , decltype(_impl_.filedir_){}
    , decltype(_impl_.filetime_){}
    , decltype(_impl_.md5_){}
    , decltype(_impl_.local_path_){}
    , decltype(_impl_.password_){}
    , decltype(_impl_.filesize_){int64_t{0}}
    , decltype(_impl_.net_size_){int64_t{0}}
    , decltype(_impl_.ori_size_){int64_t{0}}
    , decltype(_impl_.is_dir_){false}
    , decltype(_impl_.is_enc_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.filename_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.filename_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.filedir_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.filedir_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.filetime_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.filetime_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.md5_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.md5_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.local_path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.local_path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.password_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.password_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

XFileInfo::~XFileInfo() {
  // @@protoc_insertion_point(destructor:xdisk.XFileInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void XFileInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.filename_.Destroy();
  _impl_.filedir_.Destroy();
  _impl_.filetime_.Destroy();
  _impl_.md5_.Destroy();
  _impl_.local_path_.Destroy();
  _impl_.password_.Destroy();
}

void XFileInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void XFileInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:xdisk.XFileInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.filename_.ClearToEmpty();
  _impl_.filedir_.ClearToEmpty();
  _impl_.filetime_.ClearToEmpty();
  _impl_.md5_.ClearToEmpty();
  _impl_.local_path_.ClearToEmpty();
  _impl_.password_.ClearToEmpty();
  ::memset(&_impl_.filesize_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.is_enc_) -
      reinterpret_cast<char*>(&_impl_.filesize_)) + sizeof(_impl_.is_enc_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* XFileInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes filename = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_filename();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes filedir = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_filedir();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 filesize = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.filesize_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string filetime = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_filetime();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "xdisk.XFileInfo.filetime"));
        } else
          goto handle_unusual;
        continue;
      // bool is_dir = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.is_dir_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes md5 = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_md5();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes local_path = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_local_path();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 net_size = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.net_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool is_enc = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          _impl_.is_enc_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 ori_size = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 80)) {
          _impl_.ori_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes password = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          auto str = _internal_mutable_password();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* XFileInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:xdisk.XFileInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes filename = 1;
  if (!this->_internal_filename().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_filename(), target);
  }

  // bytes filedir = 2;
  if (!this->_internal_filedir().empty()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_filedir(), target);
  }

  // int64 filesize = 3;
  if (this->_internal_filesize() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_filesize(), target);
  }

  // string filetime = 4;
  if (!this->_internal_filetime().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_filetime().data(), static_cast<int>(this->_internal_filetime().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "xdisk.XFileInfo.filetime");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_filetime(), target);
  }

  // bool is_dir = 5;
  if (this->_internal_is_dir() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(5, this->_internal_is_dir(), target);
  }

  // bytes md5 = 6;
  if (!this->_internal_md5().empty()) {
    target = stream->WriteBytesMaybeAliased(
        6, this->_internal_md5(), target);
  }

  // bytes local_path = 7;
  if (!this->_internal_local_path().empty()) {
    target = stream->WriteBytesMaybeAliased(
        7, this->_internal_local_path(), target);
  }

  // int64 net_size = 8;
  if (this->_internal_net_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(8, this->_internal_net_size(), target);
  }

  // bool is_enc = 9;
  if (this->_internal_is_enc() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(9, this->_internal_is_enc(), target);
  }

  // int64 ori_size = 10;
  if (this->_internal_ori_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(10, this->_internal_ori_size(), target);
  }

  // bytes password = 11;
  if (!this->_internal_password().empty()) {
    target = stream->WriteBytesMaybeAliased(
        11, this->_internal_password(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:xdisk.XFileInfo)
  return target;
}

size_t XFileInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:xdisk.XFileInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes filename = 1;
  if (!this->_internal_filename().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_filename());
  }

  // bytes filedir = 2;
  if (!this->_internal_filedir().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_filedir());
  }

  // string filetime = 4;
  if (!this->_internal_filetime().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_filetime());
  }

  // bytes md5 = 6;
  if (!this->_internal_md5().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_md5());
  }

  // bytes local_path = 7;
  if (!this->_internal_local_path().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_local_path());
  }

  // bytes password = 11;
  if (!this->_internal_password().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_password());
  }

  // int64 filesize = 3;
  if (this->_internal_filesize() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_filesize());
  }

  // int64 net_size = 8;
  if (this->_internal_net_size() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_net_size());
  }

  // int64 ori_size = 10;
  if (this->_internal_ori_size() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_ori_size());
  }

  // bool is_dir = 5;
  if (this->_internal_is_dir() != 0) {
    total_size += 1 + 1;
  }

  // bool is_enc = 9;
  if (this->_internal_is_enc() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData XFileInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    XFileInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*XFileInfo::GetClassData() const { return &_class_data_; }


void XFileInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<XFileInfo*>(&to_msg);
  auto& from = static_cast<const XFileInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:xdisk.XFileInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_filename().empty()) {
    _this->_internal_set_filename(from._internal_filename());
  }
  if (!from._internal_filedir().empty()) {
    _this->_internal_set_filedir(from._internal_filedir());
  }
  if (!from._internal_filetime().empty()) {
    _this->_internal_set_filetime(from._internal_filetime());
  }
  if (!from._internal_md5().empty()) {
    _this->_internal_set_md5(from._internal_md5());
  }
  if (!from._internal_local_path().empty()) {
    _this->_internal_set_local_path(from._internal_local_path());
  }
  if (!from._internal_password().empty()) {
    _this->_internal_set_password(from._internal_password());
  }
  if (from._internal_filesize() != 0) {
    _this->_internal_set_filesize(from._internal_filesize());
  }
  if (from._internal_net_size() != 0) {
    _this->_internal_set_net_size(from._internal_net_size());
  }
  if (from._internal_ori_size() != 0) {
    _this->_internal_set_ori_size(from._internal_ori_size());
  }
  if (from._internal_is_dir() != 0) {
    _this->_internal_set_is_dir(from._internal_is_dir());
  }
  if (from._internal_is_enc() != 0) {
    _this->_internal_set_is_enc(from._internal_is_enc());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void XFileInfo::CopyFrom(const XFileInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xdisk.XFileInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool XFileInfo::IsInitialized() const {
  return true;
}

void XFileInfo::InternalSwap(XFileInfo* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.filename_, lhs_arena,
      &other->_impl_.filename_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.filedir_, lhs_arena,
      &other->_impl_.filedir_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.filetime_, lhs_arena,
      &other->_impl_.filetime_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.md5_, lhs_arena,
      &other->_impl_.md5_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.local_path_, lhs_arena,
      &other->_impl_.local_path_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.password_, lhs_arena,
      &other->_impl_.password_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(XFileInfo, _impl_.is_enc_)
      + sizeof(XFileInfo::_impl_.is_enc_)
      - PROTOBUF_FIELD_OFFSET(XFileInfo, _impl_.filesize_)>(
          reinterpret_cast<char*>(&_impl_.filesize_),
          reinterpret_cast<char*>(&other->_impl_.filesize_));
}

::PROTOBUF_NAMESPACE_ID::Metadata XFileInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_xms_5fdisk_5fclient_5fgui_2eproto_getter, &descriptor_table_xms_5fdisk_5fclient_5fgui_2eproto_once,
      file_level_metadata_xms_5fdisk_5fclient_5fgui_2eproto[3]);
}

// ===================================================================

class XFileInfoList::_Internal {
 public:
};

XFileInfoList::XFileInfoList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:xdisk.XFileInfoList)
}
XFileInfoList::XFileInfoList(const XFileInfoList& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  XFileInfoList* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.files_){from._impl_.files_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:xdisk.XFileInfoList)
}

inline void XFileInfoList::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.files_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

XFileInfoList::~XFileInfoList() {
  // @@protoc_insertion_point(destructor:xdisk.XFileInfoList)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void XFileInfoList::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.files_.~RepeatedPtrField();
}

void XFileInfoList::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void XFileInfoList::Clear() {
// @@protoc_insertion_point(message_clear_start:xdisk.XFileInfoList)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.files_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* XFileInfoList::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .xdisk.XFileInfo files = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_files(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* XFileInfoList::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:xdisk.XFileInfoList)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .xdisk.XFileInfo files = 4;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_files_size()); i < n; i++) {
    const auto& repfield = this->_internal_files(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(4, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:xdisk.XFileInfoList)
  return target;
}

size_t XFileInfoList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:xdisk.XFileInfoList)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .xdisk.XFileInfo files = 4;
  total_size += 1UL * this->_internal_files_size();
  for (const auto& msg : this->_impl_.files_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData XFileInfoList::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    XFileInfoList::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*XFileInfoList::GetClassData() const { return &_class_data_; }


void XFileInfoList::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<XFileInfoList*>(&to_msg);
  auto& from = static_cast<const XFileInfoList&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:xdisk.XFileInfoList)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.files_.MergeFrom(from._impl_.files_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void XFileInfoList::CopyFrom(const XFileInfoList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xdisk.XFileInfoList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool XFileInfoList::IsInitialized() const {
  return true;
}

void XFileInfoList::InternalSwap(XFileInfoList* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.files_.InternalSwap(&other->_impl_.files_);
}

::PROTOBUF_NAMESPACE_ID::Metadata XFileInfoList::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_xms_5fdisk_5fclient_5fgui_2eproto_getter, &descriptor_table_xms_5fdisk_5fclient_5fgui_2eproto_once,
      file_level_metadata_xms_5fdisk_5fclient_5fgui_2eproto[4]);
}

// ===================================================================

class XFileTask::_Internal {
 public:
  static const ::xdisk::XFileInfo& file(const XFileTask* msg);
};

const ::xdisk::XFileInfo&
XFileTask::_Internal::file(const XFileTask* msg) {
  return *msg->_impl_.file_;
}
XFileTask::XFileTask(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:xdisk.XFileTask)
}
XFileTask::XFileTask(const XFileTask& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  XFileTask* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.tasktime_){}
    , decltype(_impl_.file_){nullptr}
    , decltype(_impl_.index_){}
    , decltype(_impl_.is_complete_){}
    , decltype(_impl_.is_sec_){}
    , decltype(_impl_.is_upload_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.tasktime_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.tasktime_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_tasktime().empty()) {
    _this->_impl_.tasktime_.Set(from._internal_tasktime(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_file()) {
    _this->_impl_.file_ = new ::xdisk::XFileInfo(*from._impl_.file_);
  }
  ::memcpy(&_impl_.index_, &from._impl_.index_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.is_upload_) -
    reinterpret_cast<char*>(&_impl_.index_)) + sizeof(_impl_.is_upload_));
  // @@protoc_insertion_point(copy_constructor:xdisk.XFileTask)
}

inline void XFileTask::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.tasktime_){}
    , decltype(_impl_.file_){nullptr}
    , decltype(_impl_.index_){0}
    , decltype(_impl_.is_complete_){false}
    , decltype(_impl_.is_sec_){false}
    , decltype(_impl_.is_upload_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.tasktime_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.tasktime_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

XFileTask::~XFileTask() {
  // @@protoc_insertion_point(destructor:xdisk.XFileTask)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void XFileTask::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.tasktime_.Destroy();
  if (this != internal_default_instance()) delete _impl_.file_;
}

void XFileTask::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void XFileTask::Clear() {
// @@protoc_insertion_point(message_clear_start:xdisk.XFileTask)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.tasktime_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.file_ != nullptr) {
    delete _impl_.file_;
  }
  _impl_.file_ = nullptr;
  ::memset(&_impl_.index_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.is_upload_) -
      reinterpret_cast<char*>(&_impl_.index_)) + sizeof(_impl_.is_upload_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* XFileTask::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 index = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.index_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string tasktime = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_tasktime();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "xdisk.XFileTask.tasktime"));
        } else
          goto handle_unusual;
        continue;
      // bool is_complete = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.is_complete_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool is_sec = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.is_sec_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .xdisk.XFileInfo file = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          ptr = ctx->ParseMessage(_internal_mutable_file(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool is_upload = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 80)) {
          _impl_.is_upload_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* XFileTask::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:xdisk.XFileTask)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 index = 1;
  if (this->_internal_index() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_index(), target);
  }

  // string tasktime = 6;
  if (!this->_internal_tasktime().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_tasktime().data(), static_cast<int>(this->_internal_tasktime().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "xdisk.XFileTask.tasktime");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_tasktime(), target);
  }

  // bool is_complete = 7;
  if (this->_internal_is_complete() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(7, this->_internal_is_complete(), target);
  }

  // bool is_sec = 8;
  if (this->_internal_is_sec() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(8, this->_internal_is_sec(), target);
  }

  // .xdisk.XFileInfo file = 9;
  if (this->_internal_has_file()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(9, _Internal::file(this),
        _Internal::file(this).GetCachedSize(), target, stream);
  }

  // bool is_upload = 10;
  if (this->_internal_is_upload() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(10, this->_internal_is_upload(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:xdisk.XFileTask)
  return target;
}

size_t XFileTask::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:xdisk.XFileTask)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string tasktime = 6;
  if (!this->_internal_tasktime().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_tasktime());
  }

  // .xdisk.XFileInfo file = 9;
  if (this->_internal_has_file()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.file_);
  }

  // int32 index = 1;
  if (this->_internal_index() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_index());
  }

  // bool is_complete = 7;
  if (this->_internal_is_complete() != 0) {
    total_size += 1 + 1;
  }

  // bool is_sec = 8;
  if (this->_internal_is_sec() != 0) {
    total_size += 1 + 1;
  }

  // bool is_upload = 10;
  if (this->_internal_is_upload() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData XFileTask::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    XFileTask::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*XFileTask::GetClassData() const { return &_class_data_; }


void XFileTask::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<XFileTask*>(&to_msg);
  auto& from = static_cast<const XFileTask&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:xdisk.XFileTask)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_tasktime().empty()) {
    _this->_internal_set_tasktime(from._internal_tasktime());
  }
  if (from._internal_has_file()) {
    _this->_internal_mutable_file()->::xdisk::XFileInfo::MergeFrom(
        from._internal_file());
  }
  if (from._internal_index() != 0) {
    _this->_internal_set_index(from._internal_index());
  }
  if (from._internal_is_complete() != 0) {
    _this->_internal_set_is_complete(from._internal_is_complete());
  }
  if (from._internal_is_sec() != 0) {
    _this->_internal_set_is_sec(from._internal_is_sec());
  }
  if (from._internal_is_upload() != 0) {
    _this->_internal_set_is_upload(from._internal_is_upload());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void XFileTask::CopyFrom(const XFileTask& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xdisk.XFileTask)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool XFileTask::IsInitialized() const {
  return true;
}

void XFileTask::InternalSwap(XFileTask* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.tasktime_, lhs_arena,
      &other->_impl_.tasktime_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(XFileTask, _impl_.is_upload_)
      + sizeof(XFileTask::_impl_.is_upload_)
      - PROTOBUF_FIELD_OFFSET(XFileTask, _impl_.file_)>(
          reinterpret_cast<char*>(&_impl_.file_),
          reinterpret_cast<char*>(&other->_impl_.file_));
}

::PROTOBUF_NAMESPACE_ID::Metadata XFileTask::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_xms_5fdisk_5fclient_5fgui_2eproto_getter, &descriptor_table_xms_5fdisk_5fclient_5fgui_2eproto_once,
      file_level_metadata_xms_5fdisk_5fclient_5fgui_2eproto[5]);
}

// ===================================================================

class XFileTaskList::_Internal {
 public:
};

XFileTaskList::XFileTaskList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:xdisk.XFileTaskList)
}
XFileTaskList::XFileTaskList(const XFileTaskList& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  XFileTaskList* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.uploads_){from._impl_.uploads_}
    , decltype(_impl_.downloads_){from._impl_.downloads_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:xdisk.XFileTaskList)
}

inline void XFileTaskList::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.uploads_){arena}
    , decltype(_impl_.downloads_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

XFileTaskList::~XFileTaskList() {
  // @@protoc_insertion_point(destructor:xdisk.XFileTaskList)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void XFileTaskList::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.uploads_.~RepeatedPtrField();
  _impl_.downloads_.~RepeatedPtrField();
}

void XFileTaskList::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void XFileTaskList::Clear() {
// @@protoc_insertion_point(message_clear_start:xdisk.XFileTaskList)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.uploads_.Clear();
  _impl_.downloads_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* XFileTaskList::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .xdisk.XFileTask uploads = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_uploads(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .xdisk.XFileTask downloads = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_downloads(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* XFileTaskList::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:xdisk.XFileTaskList)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .xdisk.XFileTask uploads = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_uploads_size()); i < n; i++) {
    const auto& repfield = this->_internal_uploads(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .xdisk.XFileTask downloads = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_downloads_size()); i < n; i++) {
    const auto& repfield = this->_internal_downloads(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:xdisk.XFileTaskList)
  return target;
}

size_t XFileTaskList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:xdisk.XFileTaskList)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .xdisk.XFileTask uploads = 1;
  total_size += 1UL * this->_internal_uploads_size();
  for (const auto& msg : this->_impl_.uploads_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .xdisk.XFileTask downloads = 2;
  total_size += 1UL * this->_internal_downloads_size();
  for (const auto& msg : this->_impl_.downloads_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData XFileTaskList::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    XFileTaskList::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*XFileTaskList::GetClassData() const { return &_class_data_; }


void XFileTaskList::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<XFileTaskList*>(&to_msg);
  auto& from = static_cast<const XFileTaskList&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:xdisk.XFileTaskList)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.uploads_.MergeFrom(from._impl_.uploads_);
  _this->_impl_.downloads_.MergeFrom(from._impl_.downloads_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void XFileTaskList::CopyFrom(const XFileTaskList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:xdisk.XFileTaskList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool XFileTaskList::IsInitialized() const {
  return true;
}

void XFileTaskList::InternalSwap(XFileTaskList* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.uploads_.InternalSwap(&other->_impl_.uploads_);
  _impl_.downloads_.InternalSwap(&other->_impl_.downloads_);
}

::PROTOBUF_NAMESPACE_ID::Metadata XFileTaskList::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_xms_5fdisk_5fclient_5fgui_2eproto_getter, &descriptor_table_xms_5fdisk_5fclient_5fgui_2eproto_once,
      file_level_metadata_xms_5fdisk_5fclient_5fgui_2eproto[6]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace xdisk
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::xdisk::XDiskInfo*
Arena::CreateMaybeMessage< ::xdisk::XDiskInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::xdisk::XDiskInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::xdisk::XGetDirReq*
Arena::CreateMaybeMessage< ::xdisk::XGetDirReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::xdisk::XGetDirReq >(arena);
}
template<> PROTOBUF_NOINLINE ::xdisk::XFileSlice*
Arena::CreateMaybeMessage< ::xdisk::XFileSlice >(Arena* arena) {
  return Arena::CreateMessageInternal< ::xdisk::XFileSlice >(arena);
}
template<> PROTOBUF_NOINLINE ::xdisk::XFileInfo*
Arena::CreateMaybeMessage< ::xdisk::XFileInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::xdisk::XFileInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::xdisk::XFileInfoList*
Arena::CreateMaybeMessage< ::xdisk::XFileInfoList >(Arena* arena) {
  return Arena::CreateMessageInternal< ::xdisk::XFileInfoList >(arena);
}
template<> PROTOBUF_NOINLINE ::xdisk::XFileTask*
Arena::CreateMaybeMessage< ::xdisk::XFileTask >(Arena* arena) {
  return Arena::CreateMessageInternal< ::xdisk::XFileTask >(arena);
}
template<> PROTOBUF_NOINLINE ::xdisk::XFileTaskList*
Arena::CreateMaybeMessage< ::xdisk::XFileTaskList >(Arena* arena) {
  return Arena::CreateMessageInternal< ::xdisk::XFileTaskList >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
