// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: xmsg_type.proto
// Protobuf C++ Version: 7.34.1

#include "xmsg_type.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace xmsg {
}  // namespace xmsg
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_xmsg_5ftype_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_xmsg_5ftype_2eproto = nullptr;
const ::uint32_t TableStruct_xmsg_5ftype_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* PROTOBUF_NULLABLE schemas = nullptr;
static constexpr ::_pb::Message* PROTOBUF_NONNULL const* PROTOBUF_NULLABLE
    file_default_instances = nullptr;
const char descriptor_table_protodef_xmsg_5ftype_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017xmsg_type.proto\022\004xmsg*\252\005\n\007MsgType\022\023\n\017N"
    "ONE_DO_NOT_USE\020\000\022\021\n\rMSG_LOGIN_REQ\020\001\022\021\n\rM"
    "SG_LOGIN_RES\020\002\022\017\n\013MSG_DIR_REQ\020\003\022\017\n\013MSG_D"
    "IR_RES\020\004\022\024\n\020MSG_REGISTER_REQ\020\005\022\024\n\020MSG_RE"
    "GISTER_RES\020\006\022\027\n\023MSG_GET_SERVICE_REQ\020\007\022\027\n"
    "\023MSG_GET_SERVICE_RES\020\010\022\027\n\023MSG_SAVE_CONFI"
    "G_REQ\020\t\022\027\n\023MSG_SAVE_CONFIG_RES\020\n\022\027\n\023MSG_"
    "LOAD_CONFIG_REQ\020\013\022\027\n\023MSG_LOAD_CONFIG_RES"
    "\020\014\022\033\n\027MSG_LOAD_ALL_CONFIG_REQ\020\r\022\033\n\027MSG_L"
    "OAD_ALL_CONFIG_RES\020\016\022\026\n\022MSG_DEL_CONFIG_R"
    "EQ\020\017\022\026\n\022MSG_DEL_CONFIG_RES\020\020\022\024\n\020MSG_ADD_"
    "USER_REQ\020\021\022\024\n\020MSG_ADD_USER_RES\020\022\022\033\n\027MSG_"
    "CHANGE_PASSWORD_REQ\020\023\022\034\n\027MSG_CHANGE_PASS"
    "WORD_RES\020\320\001\022\030\n\023MSG_CHECK_TOKEN_REQ\020\321\001\022\030\n"
    "\023MSG_CHECK_TOKEN_RES\020\322\001\022\024\n\017MSG_ADD_LOG_R"
    "EQ\020\323\001\022\035\n\027MSG_GET_OUT_SERVICE_REQ\020\374\377\003\022\035\n\027"
    "MSG_GET_OUT_SERVICE_RES\020\375\377\003\022\023\n\rMSG_HEART"
    "_REQ\020\376\377\003\022\022\n\014MSG_MAX_TYPE\020\377\377\003b\006proto3"
};
static ::absl::once_flag descriptor_table_xmsg_5ftype_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_xmsg_5ftype_2eproto = {
    false,
    false,
    716,
    descriptor_table_protodef_xmsg_5ftype_2eproto,
    "xmsg_type.proto",
    &descriptor_table_xmsg_5ftype_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_xmsg_5ftype_2eproto::offsets,
    file_level_enum_descriptors_xmsg_5ftype_2eproto,
    file_level_service_descriptors_xmsg_5ftype_2eproto,
};
namespace xmsg {
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
MsgType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_xmsg_5ftype_2eproto);
  return file_level_enum_descriptors_xmsg_5ftype_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t MsgType_internal_data_[] = {
    1310720u, 524288u, 65532u, 210u, 65534u, 209u, 211u, 65533u, 65535u, 208u, };
// @@protoc_insertion_point(namespace_scope)
}  // namespace xmsg
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_xmsg_5ftype_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
