// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: xmsg_type.proto
// Protobuf C++ Version: 7.34.1

#ifndef xmsg_5ftype_2eproto_2epb_2eh
#define xmsg_5ftype_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_xmsg_5ftype_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_xmsg_5ftype_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_xmsg_5ftype_2eproto;
}  // extern "C"
namespace xmsg {
enum MsgType : int;
extern const uint32_t MsgType_internal_data_[];
}  // namespace xmsg
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::xmsg::MsgType_internal_data_>
    internal::EnumTraitsImpl::value<::xmsg::MsgType>;
}  // namespace protobuf
}  // namespace google

namespace xmsg {
enum MsgType : int {
  NONE_DO_NOT_USE = 0,
  MSG_LOGIN_REQ = 1,
  MSG_LOGIN_RES = 2,
  MSG_DIR_REQ = 3,
  MSG_DIR_RES = 4,
  MSG_REGISTER_REQ = 5,
  MSG_REGISTER_RES = 6,
  MSG_GET_SERVICE_REQ = 7,
  MSG_GET_SERVICE_RES = 8,
  MSG_SAVE_CONFIG_REQ = 9,
  MSG_SAVE_CONFIG_RES = 10,
  MSG_LOAD_CONFIG_REQ = 11,
  MSG_LOAD_CONFIG_RES = 12,
  MSG_LOAD_ALL_CONFIG_REQ = 13,
  MSG_LOAD_ALL_CONFIG_RES = 14,
  MSG_DEL_CONFIG_REQ = 15,
  MSG_DEL_CONFIG_RES = 16,
  MSG_ADD_USER_REQ = 17,
  MSG_ADD_USER_RES = 18,
  MSG_CHANGE_PASSWORD_REQ = 19,
  MSG_CHANGE_PASSWORD_RES = 208,
  MSG_CHECK_TOKEN_REQ = 209,
  MSG_CHECK_TOKEN_RES = 210,
  MSG_ADD_LOG_REQ = 211,
  MSG_GET_OUT_SERVICE_REQ = 65532,
  MSG_GET_OUT_SERVICE_RES = 65533,
  MSG_HEART_REQ = 65534,
  MSG_MAX_TYPE = 65535,
  MsgType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  MsgType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t MsgType_internal_data_[];
inline constexpr MsgType MsgType_MIN =
    static_cast<MsgType>(0);
inline constexpr MsgType MsgType_MAX =
    static_cast<MsgType>(65535);
[[nodiscard]] inline bool MsgType_IsValid(int value) {
  return ::google::protobuf::internal::ValidateEnum(value, MsgType_internal_data_);
}
inline constexpr int MsgType_ARRAYSIZE = 65535 + 1;
[[nodiscard]] const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL
MsgType_descriptor();
[[nodiscard]] inline auto ProtobufInternalGetEnumDescriptor(MsgType) {
  return MsgType_descriptor();
}
template <typename T>
[[nodiscard]] const ::std::string& MsgType_Name(T value) {
  static_assert(::std::is_same<T, MsgType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to MsgType_Name().");
  return ::google::protobuf::internal::NameOfEnum(MsgType_descriptor(), value);
}
[[nodiscard]] inline bool MsgType_Parse(
    ::absl::string_view name, MsgType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<MsgType>(MsgType_descriptor(), name,
                                           value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace xmsg


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::xmsg::MsgType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::xmsg::MsgType>() {
  return ::xmsg::MsgType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // xmsg_5ftype_2eproto_2epb_2eh
